### ISSUE TITLE
Add alternative Python implementation in README

### ISSUE THREAD

**Issue by aidarkhanov** [ai/nanoid#103]
Ported many tests and code follows new Nano ID 2.0 [https://github.com/aidarkhanov/py-nanoid](https://github.com/aidarkhanov/py-nanoid)

Though, I have discussed with Paul Yuan, maintainer of [https://github.com/puyuan/py-nanoid](https://github.com/puyuan/py-nanoid), an update of his project to the new version and we have agreed upon a merge.

Nevertheless, my project has one more case - port of Nano ID dictionary to Python.

Why adding another implementation to the list?
In my opinion, having another point of view and providing another option to a user is great opportunity to increase popularity of Nano ID.

**Comment by ai** [comment]
I prefer to keep only single implementation (but I am OK to replace outdated project to a new one).

If you want to keep 2 implementations, you will need to describe the difference very short and clear (it is incredibly hard to do in most of the cases, this is why I prefer to keep only single implementation, but you could try).

**Comment by aidarkhanov** [comment]
I think I can try. Anyone can use puyuan's version when someone only needs basic functionality like having only generate function. Whereas, when users start to need having extra packages, like prevent_misreadings() function or more alphabets in their toolkit, they can easily hot replace puyuan's version with mine as we keep the same API.

**Comment by ai** [comment]
Why not put all extra features to the origin package? Python does not have the npm problem of bloating JS bundle.

**Comment by aidarkhanov** [comment]
Unfortunately, Paul wants to keep his library short and simple and rejected my attempt to merge extra packages inside. So we have came up only with pulling fresh code base of generation function to his repository.

**Comment by ai** [comment]
Maybe we should put to additional library only extra features?

**Comment by aidarkhanov** [comment]
Maybe so, just can't think of a Github repo name of Python Nano ID dictionary. py-nanoid-dictionary?

**Comment by ai** [comment]
`py-nanoid-dictionary` :+1:

**Comment by aidarkhanov** [comment]
[https://github.com/aidarkhanov/py-nanoid-dictionary](https://github.com/aidarkhanov/py-nanoid-dictionary) And we are live!

**Comment by ai** [comment]
Great. Send PR
