### ISSUE TITLE
Mark the package as side-effect-free with "sideEffects": false?

### ISSUE THREAD

**Issue by xiaody** [ai/nanoid#108]
https://webpack.js.org/guides/tree-shaking/#mark-the-file-as-side-effect-free

**Comment by ai** [comment]
@xiaody sure. Do you want to send PR to save your name in project history?

**Comment by xiaody** [comment]
> Do you want to send PR to save your name in project history?

That would be cool. I opened a pull request #109 .

**Comment by ai** [comment]
> Why? This package is made to provide only necessary with path imports.

Yeap, there is no big benefits for us. But I like to be semantic correct. We do not have side effects, so this flag is semantic correct. Maybe in the future bundler will use it in some different forms.

> sideEffects will not introduce anything here except unexpected bugs.

What kind of bugs we can find?

**Comment by TrySound** [comment]
Maybe nothing in this project but I got some failures previously. We cannot control side effects appearance in javascript. This flag just makes the code silently broken. So if you will ever introduce some small side effect and will forget to tweak this flag the package will be broken.

Semantic is not the right word. It's a hack. It was introduced to hack transpiled code and lack of scope analysis in webpack. Good semantic is well analysable code. I think it already is in this project.

**Comment by ai** [comment]
> So if you will ever introduce some small side effect and will forget to tweak this flag the package will be broken.

Public API of this module is to no having side effects. So I consider side effects as a bug.

In this case, having an issue will help us to find this “side effects”.

> Semantic is not the right word. It's a hack. 

You are thinking about `sideEffect` only as a hack for tree shaking. I see widely on it. For me, it is like `"use strict"`. The promise of using some best practices. For me, tree shaking hack is just one example of using this promise.

Of course, both interpretations are correct.

**Comment by TrySound** [comment]
Well, user will find this bug. Not you. Find another ways to test side effects. This one is not the right one. `use strict` is runtime thing and it for sure may be covered with tests.

**Comment by ai** [comment]
> Well, user will find this bug.

What exact bugs are we talking about?

**Comment by TrySound** [comment]
Some modules without exports are usually side effectful. They will be broken. css files provided in the package like react-virtualized does. They will be broken unless you will specify them as side effect. It's another hack to control the code. Let it be just pure code without side effects in configuration.

**Comment by ai** [comment]
@TrySound we do not have CSS. I need an exact possible bug which could happen with Nano ID.

It is very dangerous to think about abstract problems without any details since we will be controlled by our fears, not rational reasons (like issue probability or possible damage).

**Comment by TrySound** [comment]
My point is that you should not include this flag unless you really need it to fix the problem with the code. There is no problem now. You are talking about abstract semantic and added this field without rational reasons. This is dangerous too.

**Comment by ai** [comment]
> My point is that you should not include this flag unless you really need it to fix the problem with the code.

Since both of our reasons do not have any practical result (there is no real benefits, but also there is no real issues) they are both subjective.

In this subjective reason of maintainer is more important.

If we will have any practical reasons, I will change my mind.
