### ISSUE TITLE
How to use this as _id?

### ISSUE THREAD

**Issue by teknolojia** [ai/nanoid#113]
I have been using [shortId ](https://github.com/dylang/shortid/issues/142#issuecomment-471030670) and according to its original author it is now deprecated.
I used to using it as follows and worked fine.
`    _id: {
        type: String,
        default: shortId.generate
    },`
But when I replace it with nanoid the first **save()** works fine but I get this error when I want to insert another record. **"E11000 duplicate key error collection: mydbName.myCollection index: _id_ dup key: { : \"vmpz29OlAk\"** I used it as follows:
`    _id: {
        type: String,
        default: nanoId(10)
    },`
This is the static method attached in my model:
`mySchema.statics.addItem = function (input) {
    return new this(input).save();
};`

And this is how I used the function in another file:
`MyModel.addItem(input);`

How do I solve this?

**Comment by ai** [comment]
```js
_id: {
  type: String,
  default: () => nanoId(10)
},
```

**Comment by ai** [comment]
What database do you use?

Maybe we should add docs

**Comment by teknolojia** [comment]
MongoDb. @ai Thanks. It worked.

**Comment by ai** [comment]
@teknolojia do you want to save PR with `MongoDB` instructions in `Usage` section to save your name in the project history?

**Comment by teknolojia** [comment]
Okey I got you.

**Comment by teknolojia** [comment]
I did it.
