### ISSUE TITLE
Crash Google Chrome Tab with nanoid

### ISSUE THREAD

**Issue by erikknaake** [ai/nanoid#115]
So I am using nanoid to generate passwords in chrome, the default code
`const nanoid = require('nanoid');
return nanoid(20);
`

Works fine, however when I want to use a custom alphabet (I want user to control what characters are allowed) the following code makes the Chrome tab hang forever:
`const generate = require('nanoid/generate');
let alphabet = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789';
generate(alphabet, 20);`

Is this me doing something wring or is it a serios issue in nanoind? I have tried other custom alphabets as well.

Note this is using TypeScript

**Comment by ai** [comment]
Very strange, I have the same code in my demo test and it's works.

Does it crash other browsers on your machine? Does it crash Chrome on different machine?

**Comment by erikknaake** [comment]
So I just tried again (after a restart) and I can no longer reproduce this issue. I will reopen an issue if the issue occurs again
