### ISSUE TITLE
removing code increases size?

### ISSUE THREAD

**Issue by chase-moskal** [ai/nanoid#118]
hello friends,

[in this commit](https://github.com/chase-moskal/nanoid/commit/25f738faf0afc7fc11077b164a9f51f7c11ac2fd), i have removed some code from `index.browser.js`

- confusingly, this causes `size-limit` to report that the size has ***increased***
- also, reducing `index.browser.js` is causing the reported size of `index.js` to increase -- a different file
- in additon, i also find that if i remove any other block of code, the size limit correctly reports a decrease in size -- the confusing increase only occurs when i remove any code from the code block in question

there must be some interesting magic at play here, what am i missing?

motive: i want to remove the if clause involving `process`, in order to restore browser support

**Comment by ai** [comment]
> there must be some interesting magic at play here, what am i missing?

`process.env.NODE_ENV` will be inlined by webpack or Parcel to the current `NODE_ENV`. As a result, `if (process.env.NODE_ENV !== 'production') {` is a special construction to remove some code (warning in this case) from in production code.

By removing this code, you put this non-critical warning to production code.

> motive: i want to remove the if clause involving process, in order to restore browser support

Are you facing some real problem with browser support? In what use case?

**Comment by chase-moskal** [comment]
ah, very interesting, i appreciate the clarification!

> Are you facing some real problem with browser support? In what use case?

i'm just experimenting with upcoming workflows and doing some experiments that load *everything* as es-modules

i may be the first person to come here looking for es-module format -- but i'm sure i won't be the last!

thanks for explaining what's going on, issue closed
