### ISSUE TITLE
Prevent underscore being used as first character

### ISSUE THREAD

**Issue by SteveEdson** [ai/nanoid#120]
I'm trying to use this with PouchDB + CouchDB, however I sometimes get the error:

```
Only reserved document ids may start with underscore.
```

I noticed a similar issue was closed a couple of years ago (https://github.com/ai/nanoid/issues/28), however I feel like that was due to the request being preference, rather than an actual issue.

Thanks

**Comment by ai** [comment]
We can’t just prohibit `_` from being first, because it will affect characters distribution and will be bad for security cases.

Seems like it is better to use different alphabet for CouchDB `a-zA-Z0-9`. Do we need to add it to docs?

**Comment by SteveEdson** [comment]
Sorry for the delay. Yeah I think it would make sense for this to be highlighted in the docs.

Thanks

**Comment by ai** [comment]
@SteveEdson can you check my docs changes? 140b527

**Comment by SteveEdson** [comment]
Just added a comment within the PR, other than that, LGTM 👍. Thanks!
