### ISSUE TITLE
Documentation Helps

### ISSUE THREAD

**Issue by FabianoLothor** [ai/nanoid#125]
The docs are correct?

![image](https://user-images.githubusercontent.com/2192995/58385667-6e2bdb00-7fca-11e9-88e7-d499bd62fcd8.png)

On the first example, the docs shows `nanoid` in `key` prop.

On the second example, the docs shows `nanoid` in `id` prop.

How can I use the lib in `key` prop correctly?

**Comment by FabianoLothor** [comment]
`<Item key={'foo_' + nanoid()} />` is it a good code?

**Comment by ai** [comment]
> <Item key={'foo_' + nanoid()} /> is it a good code?

Nope, it dramatically reduces performance.

`nanoid()` will be called on every render, so `key` will be always different. React will think that you replaced node and update DOM again.

**Comment by ai** [comment]
I made docs better d8ebed1

**Comment by FabianoLothor** [comment]
> > <Item key={'foo_' + nanoid()} /> is it a good code?
> 
> Nope, it dramatically reduces performance.
> 
> `nanoid()` will be called on every render, so `key` will be always different. React will think that you replaced node and update DOM again.

Ok, now I see the problem, but... How can I using `nanoid` in a `array.map()` correctly?

Generating the function before the map, solves the problem in the next re-renders?

**Comment by ai** [comment]
> Generating the id before the map, and calling it inside, solves the problem on the nexts re-renders?

Yeap. Show me the code.

**Comment by FabianoLothor** [comment]
Following your explanations, I think in something like this:

```javascript
import React, { useState } from 'react';
import generateUUID from 'nanoid';

const fruitList = ['apple', 'banana', 'orange'];

const Foo = () => {
  const [uuid, setUUID] = useState(generateUUID());

  return (
    <ul>
      fruitList.map((fruit, index) => {
        let keyItem = uuid + '_fruit-item_' + index;

        // return (<li key={uuid + '_fruit-item_' + index}>fruit</li>); // bad
        return (<li key={keyItem}>fruit</li>); // good
      };
    <ul>
  );
}

export default Foo;
```

**Comment by ai** [comment]
Best way is to use real ID. In this example it will be `key={fruit}`.

Slow me real days to suggest you what to use as ID.

**Comment by FabianoLothor** [comment]
> Best way is to use real ID. In this example it will be `key={fruit}`.
> 
> Slow me real days to suggest you what to use as ID.

Ok, maybe the example is not one of the betters, sometimes fruit will not be a string. The question it is about this cases.

Are you suggest `key={'someIdentifier' + index}`?

**Comment by ai** [comment]
Nope, index of not a solution. `key` helps React to detect what was changed in array. If you moved stay in to the end, React will detect it by `key` and will just move DOM node instead of re-render DOM. `index` will not help you.
