### ISSUE TITLE
Migrate from shortid

### ISSUE THREAD

**Issue by einsub** [ai/nanoid#129]
Is it possible to migrate to **nanoid** from **shortid**? I am using **shortid** as an `_id` for mongoose collections and already have many documents. The reason that I want to migrate is simply that I want to exclude `-` from _id of future documents. I guess it may have many possibilities to collide because they might be using a different algorithm.

Thank you.

**Comment by ai** [comment]
Show your current code with `shortid`

**Comment by einsub** [comment]
I'm using `shortid` like this:
```
import * as shortid from 'shortid'

export const dataSchema = new Schema({
  _id: {
    type: String,
    default: shortid.generate
  },
  //...
})
```

**Comment by ai** [comment]
Sure. Here is how you should replace this code:
https://github.com/ai/nanoid#mongoose
