### ISSUE TITLE
Uniformity tests required

### ISSUE THREAD

**Issue by Jabher** [ai/nanoid#13]
Some test is required to validate e.g. that produced strings are keeping probability of (at least) all chars same with known probability (e.g. 5%).

**Comment by gwer** [comment]
https://github.com/ai/nanoid/blob/master/test/generate.test.js#L7-L26 ?

**Comment by gwer** [comment]
https://github.com/ai/nanoid/commit/b506b392135d73fe309e8608467bd43672aa5934 ?

**Comment by Jabher** [comment]
totally missed it. thanks :)
