### ISSUE TITLE
[Question] How to format nanoid value as a UUIDv4

### ISSUE THREAD

**Issue by flpvsk** [ai/nanoid#130]
Some databases like MongoDB and MS SQL Server support UUIDv4 as a data type. I'm trying to figure out how to convert a nanoid string to the `8-4-4-4-12` string format to feed it to a db?

TLDR; how to turn this: `9OJsJKRgbwwEw7VnSW9__` into something like this: `123e4567-e89b-12d3-a456-426655440000`?

Also would be great to know how to perform the reverse operation UUIDv4 -> url-friendly base64 nanoid

**Comment by ai** [comment]
You do not need to do it. Just use UUID :). Any formatting will be more complicated.

But maybe you should just use a string field type instead?

**Comment by flpvsk** [comment]
Thanks, both suggestions would work.

>  Just use UUID :)
That's an option, yes :)

> But maybe you should just use a string field type instead?
That's what I've been doing. I'm just wondering if there are any DB-level optimizations I'll be missing out on.
