### ISSUE TITLE
No instance id

### ISSUE THREAD

**Issue by Bramzor** [ai/nanoid#131]
How does this library make sure if you run multiple workers in cluster or at the same time, that no duplicates or collisions are generated?
Some libraries use a instance or worker id for this. How does nanoid solves this?

**Comment by ai** [comment]
Nano ID uses the same method as UUID 4. It uses very hardware random with flat distribution. As result, every node of the cluster are independent (compare with randomness based on the time).

Long ID is a protection from dublications. ID size was chosen to have extremely low probability to generate two identical ID.

Here is collision probability calculator
https://zelark.github.io/nano-id-cc/
