### ISSUE TITLE
source code

### ISSUE THREAD

**Issue by atilkan** [ai/nanoid#134]
Source code is unreadable because of comments.

**Comment by ai** [comment]
Can you show an example?

**Comment by atilkan** [comment]
I arguing if jsdoc is there to help. 
https://github.com/ai/nanoid/blob/51061f084ba6beee6a6c8a7c54f1b93dffe579e8/generate.js#L4

**Comment by ai** [comment]
JSDoc was created for IDE to show a tooltip with a description when the user will type `nanoid(`. It is pretty useful for WebStorm users.

Why this comment make code unreadable?

**Comment by atilkan** [comment]
Because of crowd. It doesn't look clean. Why not just use typescript?

**Comment by ai** [comment]
TS != JSDoc.

TS will tell only about types. It will not give a description.

> crowd

Sorry, it is not a good reason. I can’t remove useful help because of this reason. 

Maybe you can find text editor plugin to hide JSDoc?

**Comment by atilkan** [comment]
I am not asking you to remove them. I am arguing and trying to learn what is the benefit. Doesn't ts give consumer tips.

**Comment by atilkan** [comment]
I just learned ts does the same thing with types. Thanks.
