### ISSUE TITLE
npm run build warnings

### ISSUE THREAD

**Issue by lapongua** [ai/nanoid#135]
I use nanoid in a storybook component and works well in the story. But when I build I get these errors:
```
src/components/index.js → dist/index.min.js...
(!) 'crypto' is imported by node_modules/nanoid/random.js, but could not be resolved – treating it as an external dependency
(!) 'crypto' is imported by crypto?commonjs-external, but could not be resolved – treating it as an external dependency
(!) No name was provided for external module 'crypto' in output.globals – guessing 'crypto'
```
How can I solve it? Thanks.

**Comment by TrySound** [comment]
Hi @lapongua Do you use rollup to build your project? You need to pass `{ browser: true }` to node resolve plugin. This will allow rollup to consume these aliases.
https://github.com/ai/nanoid/blob/master/package.json#L22-L25

**Comment by lapongua** [comment]
Thank you, works like a charm
