### ISSUE TITLE
Can I use both shortid and nonoid modules in the same node.js route also can I use More than 64 characters as input to the Algoritham??

### ISSUE THREAD

**Issue by pssvenkatrao** [ai/nanoid#142]
Problem statement is : I am currently using shortid for generating 5 digit shortid and will save it in db. db insert failing due to collision and duplicateids.
I wanted to handle this by catching the duplicate key exception when shortid been used and at that time use nanoid to generate the uniqueid.

Please suggest if I can use both shortid and nonoid in same JavaScript.

**Comment by pssvenkatrao** [comment]
var shortid = require('shortid');
shortid.characters("0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ-_");
var nanoid = require('nanoid');
const generate = require('nanoid/generate')
model.id = generate('0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ-_#~.;)(', 6);  // I wanted to use more than 64 characters as input to generate short nanoid .

**Comment by ai** [comment]
> Can I use both shortid and nonoid modules in the same node.js

You can, but I do not recommend it. The best way is to remove unsafe `shortid` and use Nano ID instead. I can say it as shortid maintainer.

It is OK to keep the old `shortid`’s ID. Use Nano ID for new IDs.

> can I use More than 64 characters as input

Yes, use `nanoid/generate` as we described in docs https://github.com/ai/nanoid#custom-alphabet-or-length
