### ISSUE TITLE
Collision probability when using Math.random

### ISSUE THREAD

**Issue by Maaartinus** [ai/nanoid#143]
I'm afraid that the read collision probability using `Math.random()` may be much higher, depending on the implementation. The [specification](https://tc39.es/ecma262/#sec-math.random) says nothing about the size of the internal state of the generator, but typically, it's rather small (for comparison, Java uses 48 bits of state).

The problem is that no matter how smart you generate the ID, the number of distinct IDs is no bigger than the number of possible states of the generator. A 48-bit state corresponds with 16-character long base64 IDs.

**Comment by ai** [comment]
Yeap. This is why `nanoid` and `nanoid/async` use hardware random generator instead of `Math.random`.

Only `nanoid/non-secure` uses `Math.random()`. Are you asking about it?

**Comment by Maaartinus** [comment]
Yes, I do. I was quickly scanning the doc and searching the issues and found nothing about it, so I wanted to make sure it's a known problem. 

I may have missed it in the doc. If so, then please add a short note. Otherwise, feel free to close this issue.

PS: No idea, how bad current javascript `Math.random()` implementations actually are, but when they're like in java, then it should be possible to generate a (birthday) collision after about 16M IDs - doable on an average computer.

**Comment by ai** [comment]
> I may have missed it in the doc. If so, then please add a short note

Yeap. It is a good idea. Do you want to send PR to save your name in history? (But I can do it too)

**Comment by Maaartinus** [comment]
I'm in a hurry now... so please do.

**Comment by ai** [comment]
Done 8aeb784

**Comment by ai** [comment]
Released in 2.1.2
