### ISSUE TITLE
ReactNative claims that expo-random is not installed in dev mode.

### ISSUE THREAD

**Issue by skaldo** [ai/nanoid#162]
When you run RN app in dev mode with attached debugger, index.browser.js gets evaluated. An exception is then thrown that expo-random is not installed.

This is due to the platform-only check, in index.browser we do not check for the presence of expo random. This check is done in `async/random.rn.js`, thus check in `index.browser.js` is imo redundant.

I do propose to remove the check from index.browser.js. This itself resolves the issue, but referencing this file from RN runtime is not good, thus I would recommend to alter package.json to provide correct index.js.

<img src="https://user-images.githubusercontent.com/396663/71902080-9afbbf80-3161-11ea-8b13-0ae0a69f8799.png" height="500">

**Comment by ai** [comment]
Why plan from error text (of using non-secure or `nanoid/async`) doesn't work in your case?

**Comment by skaldo** [comment]
Of course I do have expo-random installed and it works, but when you are in debug mode (chrome debugger attached) the index.browser.js is executed. Here we do not check for expo-random, but just throw an exception that prevents the RN application from being executed.

Fundamental issue is, that the `index.browser.js` is executed at all - this is fixed by my change in package.json.
Second issue is the check itself in index.browser.js, which is redundant with the one in `async/random.rn.js`.
My PR takes care of both things.

**Comment by skaldo** [comment]
Thanks to the help of @ai I found that there was a dependency conditionally requiring `nanoid` or `nanoid/non-secure` based on the existence of `crypto`.

An effect of this was the fact, that this library was throwing an exception in the debug mode only.

Anybody with similar problem should check the comments in the linked PR.
