### ISSUE TITLE
Suggestion: Unique sequential ids?

### ISSUE THREAD

**Issue by subzey** [ai/nanoid#169]
The current implementation is that each new id generated is completely random. Is this an implied requirement or is it something that can be dropped?

----

> Nano ID. A ... _unique_ string ID generator

```
YCiNxSy2cdhO2
PfqHMldpg0Jnj
p0cVXpow5j0nh
8qpuYY9wnUlcF
Qu_t6GElLmNZ-
```
These are unique ids. 

```
YCiNxSy2cdhO2
ZCiNxSy2cdhO2
0DiNxSy2cdhO2
1DiNxSy2cdhO2
2DiNxSy2cdhO2
```
These are also unique IDs. They're not random, but still _unique_. The sequentially incrementing IDs with a random initial state like that can be used as an `X-Idempotency-Key` or a distributed DB key or... maybe in the most cases when Nano ID is used.

The code for generating ids this way can be small and fast as it doesn't need to deal with the entropy pool too much. See [the example](https://www.typescriptlang.org/play/index.html#code/MYewdgzgLgBApmArgWxgCQIYCcAmodwwDeAUDOTAIIA2ADgBYYBGcUAMggOZT0wC8MAGwAWADRkKNBs1YAhAJZQAshggBrfjAAMTLVoCMho+IowVADwCSODmG68BAZgBM4gL4kSoSLAx1GLLACAOQGzo7CAKyCAOwAHACczMAEAGac9PIAVmrUyGAgtACOWNCIAG4A7uYAngBelLIAwgAiAKIAYgDiaJYAUgDSbEoAcgDyAAoAigBKAMoAKgCqAGoA6gAaAJoAWgC0APrBANye3tAw0BhQhALAWDW0UCAAdJysMxhgOCDIK36IOAQAAUYDglRgS3kYCgcUoWCwGBqwMwuHwcBeFmstnsAEpcacSAB6ABU8HMtBAWFgJKJMFSiDAwCg8nAMHeYMRN2swOoXB4mmc+lxxAk5FSVJgvNYMHkmi0x1lMAAPOhsHgQARMRgrDZ+fRFfIANRGkWkUymeSpKUmq43ADa8gAujAAGRqtGajFSAJyRQqdRmsUW0xMLBwDBqU4h8geUweYN82AQTTBE7BiVYKVJpUCBVK1V8uw8Q0moMxy4wI0CPzSQL2u1wR0u92ojVan0yKAKZSqNRO6MUOMUcNQRBYMCXU4Jol0trmDDIWh8kiZ7MyuV5w0qmD6PSl03EGDB84gPkvaggTjAjlwLlwHn46dAA)

**Comment by ai** [comment]
Hm, there is definitely a market for this task. But also there are a few possible questions, which can reduce marker share:

1. How to not reduce ID predictability? Should we have increment with random part and the end? Like `++prevId + random()`?
2. How to keep uniqueness across multiple clients?

**Comment by subzey** [comment]
Yup, predictability it's the largest showstopper. The [readme](https://github.com/ai/nanoid#unpredictability) advertises unpredictability and sequential numbers is definitely a bug ...for a main entry. But, say, it could be probably okay for `non-secure`.

Or probably this feature is something this project was not designed for and is something it should not do. If you decide this would be a scope creep and close this issue, I'm totally okay with that!

Adding a random value to the previous value in a finite field is more or less just generating a new random value with extra steps (if I got your idea right). Much like the Vigenère cipher with the [advantage](https://en.wikipedia.org/wiki/Advantage_(cryptography)) equals zero.

Or did you mean adding a value in a range that is much smaller that the entire "keyspace" set size?

----

The uniqueness is kept just the same way: with some very high probability (but not certainly) the initial state for each of the clients differs. Sure, the later sequential regions may overlap, but the same can happen with the each-time-random values as well

**Comment by ai** [comment]
I think the best option is to have separated `nanoid-seq` project as we have for non-offensive ID generation and dictionaries. We will promote `nanoid-seq` in the main docs.
