### ISSUE TITLE
nanoid in PHP

### ISSUE THREAD

**Issue by hidehalo** [ai/nanoid#17]
> Dear Andrey:
> 
> 	I am a PHPer,you can call me Chen.I star your nanoid lib and I checked the source code,then I make a copy from your Javascript version in PHP.
> But I have some issue in index.js,I do not understand why that is different algorithm between formart.js for generate id or I just misunderstood?
> 
> PS: Here is my PHP version nano-id, if you have time and interest,check it: https://github.com/hidehalo/nanoid-php
> 																									Thank you!!

**Comment by ai** [comment]
Hi. Great work.

I left PHP more then 6 years ago, so it is hard to me to read PHP. But `nanoid-php/src/Core.php` looks good.

**Comment by ai** [comment]
I have different algorithms in `index.js` and `format.js` just to reduce `index.js` size (the most popular way to use nanoid).

In `index.js` alphabet size is always 64. So we can write the more effective algorithm (compare to the algorithm with the dynamic alphabet).

**Comment by hidehalo** [comment]
Thx for your answer! I will try to understand the algorithms deeper then finish it. :D
