### ISSUE TITLE
Migrate to TypeScript

### ISSUE THREAD

**Issue by nainardev** [ai/nanoid#177]

**Comment by nainardev** [comment]
Atleast have ts version as Deno natively supports TS

**Comment by ai** [comment]
@nainardev it is in my closest plans.

What do you think about [Nano Events](https://github.com/ai/nanoevents/) TS support? I just released a new version of Nano Events with a new way of TS support to use it then with NanoID?

**Comment by nainardev** [comment]
Also I'm confused why there are comments having stuff like `@param`. Why?
I'm noobie

**Comment by ai** [comment]
`@param` is [TSDoc](https://typedoc.org/) (JSDoc for TypeScript).

Also, note that we eve have tests, that TS will catch [these errors](https://github.com/ai/nanoevents/blob/master/test/errors.ts). We use [check-dts](https://github.com/ai/check-dts) for it.

**Comment by ai** [comment]
The fix was released in Nano ID 3.0
