### ISSUE TITLE
Add sync react-native solution to readme

### ISSUE THREAD

**Issue by TrySound** [ai/nanoid#179]
Hi. Sync solution is found in UUID. Can work with "nanoid" entry point.
https://github.com/uuidjs/uuid/issues/375#issuecomment-591521355

**Comment by TrySound** [comment]
Looks like expo still requires async api.
https://github.com/expo/expo/issues/7209

**Comment by ai** [comment]
I updated docs 9b44531

**Comment by TrySound** [comment]
Cool, thanks!
