### ISSUE TITLE
Number of collisions

### ISSUE THREAD

**Issue by dylanirlbeck** [ai/nanoid#182]
So in the tests I see a test case for `no collisions` for 100,000 calls to `nanoid()`. From a theory perspective, how high would this number need to be to start seeing collisions? Or, since it is random, are we not able to say?

I'm also curious about what to do in the case of collisions in a real system. How can you prevent them and/or what do you in  the case of collisions?

Thanks in advance!

**Comment by ai** [comment]
We made a special calculator to answer on your question

https://zelark.github.io/nano-id-cc/
