### ISSUE TITLE
Name export

### ISSUE THREAD

**Issue by pustovalov** [ai/nanoid#187]
Hey,

https://github.com/ai/nanoid/commit/4c7548a544b73592a2b59f53caba5bc4cbab1870
When do you plan to release these changes?

https://github.com/ai/nanoid#js
```
import { nanoid } from 'nanoid'
console.log('n', nanoid)

n undefined
```

```
import nanoid from 'nanoid'
console.log('n', nanoid)

n ƒ (size) {
```

**Comment by ai** [comment]
It was not released. I took a time to think again about names for exports. `nanoid2` is not the best, but all other options have different problems.

**Comment by TriStarGod** [comment]
It took me a while to figure this out since the readme say to use `import { nanoid } from 'nanoid/async'` but only worked with `import nanoid from 'nanoid/async'`. I prefer named exports. Why not use both `export const nanoid` and `export default` ?

**Comment by TrySound** [comment]
@TriStarGod This will increase bundle size and will lead to inconsistencies in user codebase.

**Comment by ai** [comment]
Default exports in dual ESM/CJS will work in a different way than in Node.js.

As the result, it will force library authors to publish code, which will be broken in webpack.

**Comment by ai** [comment]
Nano ID 3.0 was released
