### ISSUE TITLE
Noob here... This package is compatible with the AWS Lambda running NodeJS?

### ISSUE THREAD

**Issue by LuizThiago** [ai/nanoid#188]
Hey guys!

I'm trying to use nanoid in aws lambda without success, because it warns that the variable is not a function:

`const nanoid = require('nanoid');
const AWS = require("aws-sdk")

exports.handler = async (event) => {
    var i = 10;
    while (i--) {
        console.log(nanoid());
    }
};`

the error:

`Response:
{
  "errorType": "TypeError",
  "errorMessage": "nanoid is not a function",
  "trace": [
    "TypeError: nanoid is not a function",
    "    at Runtime.exports.handler (/var/task/index.js:7:21)",
    "    at Runtime.handleOnce (/var/runtime/Runtime.js:66:25)"
  ]
}`

**Comment by ai** [comment]
How did you solve the problem? I am curious about the solution too.

**Comment by LuizThiago** [comment]
as i said, i am noob in backend... I just added the {  } around the nanoid const...

`const { nanoid } = require('nanoid');`

sorry for the inconvenience! =P

**Comment by ai** [comment]
I am noob for AWS Lambda as well :D.

`{ nanoid } = require('nanoid')` works? I didn’t release it to npm yet.

How do you add library to Lambda. Do you have some config like `package.json` with library versions?

**Comment by LuizThiago** [comment]
yeap, it works! you need to create a folder called node_modules and place inside of it, the folders of the packages you want! i usually create all the scripts/folders hierarchy in my machine, than i upload it as .zip in the aws lambda manager
