### ISSUE TITLE
Use in AWS Lambda

### ISSUE THREAD

**Issue by giovannijoao** [ai/nanoid#199]
Hi, I'm trying to use the lib in a Lambda but I'm getting the following error: 

![image](https://user-images.githubusercontent.com/17498851/77761172-61c34500-7016-11ea-9769-8faeefcb2637.png)

![image](https://user-images.githubusercontent.com/17498851/77761157-5a9c3700-7016-11ea-8201-ae5cb80ced5a.png)
Ps: I'm developing locally so I didn't test in AWS yet. 
What could it be?

**Comment by ai** [comment]
Double check the Nano ID version in your `node_modules`.

Nano ID 2.x had completely different API.

**Comment by giovannijoao** [comment]
Thanks. It worked in release 2.1.11.

**Comment by ai** [comment]
@giovannijoao Nano ID 2.1.11 is an old release.

You need to move to Nano ID 3.0. Do not go to old released. It is better to find the source of the problem.

Here is the migration guide to 3.0 https://github.com/ai/nanoid/releases/tag/3.0.0

The more likely you just need to replace `const nanoid = require('nanoid')` to `const { nanoid } = require('nanoid')`
