### ISSUE TITLE
Issue with crypto on nanoid 3.0.0

### ISSUE THREAD

**Issue by dimaslz** [ai/nanoid#201]
Hello, I don't know if is easy to fix, but I have the following problem using nanoid 3.0.0 in a project with  Typescript 3.8.3

![Screenshot 2020-03-28 at 09 52 22](https://user-images.githubusercontent.com/1536936/77819299-0d819900-70da-11ea-9162-baba0a498b4f.png)

Any idea to fix it?

Thanks!

**Comment by ai** [comment]
How do you build your webapp? What bundler do you use and what is config?

**Comment by alex-lit** [comment]
This expression is not callable - Typescript 3.8

![Uploading DeepinScreenshot_выберите-область_20200329013800.png…]()

**Comment by ai** [comment]
@alex-lit how do you build your project?

1. What if your TypeScript config?
2. It is a website or Node.js app? If it is a website, do you use a webpack or another bundler? Show bundler config.

**Comment by alex-lit** [comment]
This expression is not callable - Typescript 3.8

![](https://habrastorage.org/webt/c5/o7/lq/c5o7lqnzbuuvgxyjy1p41kpu_pc.png)

**Comment by ai** [comment]
@alex-lit did you update your import during the migration to 3.0? https://github.com/ai/nanoid/releases/tag/3.0.0

**Comment by alex-lit** [comment]
> @alex-lit how do you build your project?
> 
> 1. What if your TypeScript config?
> 2. It is a website or Node.js app? If it is a website, do you use a webpack or another bundler? Show bundler config.

config:
{
  "compilerOptions": {
    // custom
    "skipLibCheck": true,
    "checkJs": false,
    "noImplicitThis": false,
    // default
    "target": "es5",
    "module": "esnext",
    "moduleResolution": "node",
    "lib": ["esnext", "esnext.asynciterable", "dom"],
    "esModuleInterop": true,
    "experimentalDecorators": true,
    "allowJs": false,
    "sourceMap": true,
    "strict": true,
    "noImplicitAny": false,
    "noEmit": true,
    "baseUrl": ".",
    "paths": {
      "@/*": ["./src/*"],
      "~/*": ["./src/*"]
    },
    "types": [
      "@nuxt/types",
      "@nuxtjs/axios",
      "@types/jest",
      "@types/lodash",
      "@types/node",
      "@types/qs",
      "@types/vuelidate",
      "vue-i18n/types"
    ]
  },
  "exclude": ["node_modules"]
}

**Comment by TrySound** [comment]
The new version uses named exports. Not default.
```
import { nanoid } from 'nanoid'
```

**Comment by alex-lit** [comment]
> The new version uses named exports. Not default.
> 
> ```
> import { nanoid } from 'nanoid'
> ```

Thank you, it helped!

**Comment by ai** [comment]
I deleted wrong import comments to focus this issue on the problem with bundler using Node.js files for client-side JS bundle.

**Comment by dimaslz** [comment]
> How do you build your webapp? What bundler do you use and what is config?

I am working on a stenciljs project. I didn't touch anything about build, only I fix setting according this recommendations: https://stenciljs.com/docs/module-bundling.

I will try to reproduce in other Typescript project.

I will let you know any update.

Thanks!

**Comment by ai** [comment]
@dimaslz you got this issue, because Pencil removed `browser` option from Rollup. As a result, bundle stopped to use special client-side versions of the files.

Seems like they fixed it 6 days ago and the fix will be published shortly https://github.com/ionic-team/stencil/pull/2305
