### ISSUE TITLE
override @types/nanoid

### ISSUE THREAD

**Issue by 007tom** [ai/nanoid#204]
Hello

Recently I used `nanoid` in my **React** project written with **TypeScript**, so I downloaded `@types/nanoid` first,  but when `nanoid` downloaded

`import nanoid from 'nanoid'` path in `MyComponent.tsx` changed from **`node_modules/@types/nanoid/index/` to `node_modules/nanoid/index/`**, and 
`this.state = { id: props.id || '${nanoid()}'}` occurs the error:  

**`This expression is not callable.
  Type 'typeof import("/path/to/my/project/node_modules/nanoid/index")' has no call signatures.ts(2349)`**

 I have no idea to fix it, and when do same thing above with `@types/classnames` and `@types/lodash.escaperegexp`, there is no problem .

**Comment by TrySound** [comment]
Remove `@types/nanoid` package. The new version have builtin typescript support.
https://github.com/ai/nanoid/blob/master/index.d.ts

**Comment by 007tom** [comment]
Done !

@TrySound so `nanoid()` is not used properly ?
I use `nanoid` instead of  `nanoid()` and then it fixed

**Comment by ai** [comment]
I updated Migration Guide https://github.com/ai/nanoid/releases/tag/3.0.0

@007tom thanks for the report, it helped us update docs

@TrySound can we mark `@types/nanoid` as deprecated? Do you know how we can do it?

**Comment by TrySound** [comment]
No idea

**Comment by rjohnep** [comment]
broken import, use `import { nanoid } from 'nanoid'` instead
