### ISSUE TITLE
nanoid in Go

### ISSUE THREAD

**Issue by jkomyno** [ai/nanoid#21]
# Disclaimer
I am aware of https://github.com/ai/nanoid/pull/20.
The fact is that I wasn't aware of it 24 hours ago, when I started playing around with [this port](https://github.com/jkomyno/nanoid/) of mine.

# Description
I have documented well my code, added references to the original repo (you can see many Github links inside [nanoid.go](https://github.com/jkomyno/nanoid/blob/master/nanoid.go) and ported the test suite at [test/index.test.js](https://github.com/ai/nanoid/blob/master/test/index.test.js)).

The main difference with [matoous/go-nanoid](https://github.com/matoous/go-nanoid/) is that I've strictly followed the original API. Thus, I feel it would be nice to add a link to my repo just below @matoous'  

Thus the last part of README.md would become:

## Other Programming Languages

* Go
  * [matoous/go-nanoid](https://github.com/matoous/go-nanoid) (uses a different API)
  * [jkomyno/nanoid](https://github.com/jkomyno/nanoid) (uses pretty much the same API as this original repo)
* PHP
  * [hidehalo/nanoid-php](https://github.com/hidehalo/nanoid-php)

@ai, what do you thunk about it?

**Comment by matoous** [comment]
Definitely better work,

Surely add it.

Matouš Dzivjak

**Comment by jkomyno** [comment]
Thanks a lot @matoous!
PR added here: https://github.com/ai/nanoid/pull/22

**Comment by ai** [comment]
One link is always better, than two. Let’s choose one project and put it to the docs.

Should we just take @jkomyno or send PR to @matoous implementation?

**Comment by jkomyno** [comment]
Why would you suggest that one link is better than two? I'd agree with you if the APIs of the two Go projects were similar, but they aren't

**Comment by jkomyno** [comment]
BTW, if that means something to you, mine already has Travis CI up and running without issues

**Comment by ai** [comment]
The choice is always hard for users. In this case, we really don’t need 2 solutions. Can you imagine that one developer will choice one library for one project and another library for another project? Instead of given hard choice we should select the best API and promote it.

**Comment by matoous** [comment]
Well,

Decide which one, I have no arguments agains that :) although I don't want to give up on my project :( 

Matouš Dzivjak

**Comment by ai** [comment]
@jkomyno do we have any problems why we can’t end PR to @matoous project? He was the first. Also, we should be welcome for first-time open source contribution.

I could send you PostCSS stickers if you will help @matoous on his project =^_^=

**Comment by jkomyno** [comment]
It's ok for me, but I dread that my PR would almost completely overwrite his code. Uhm, @matoous, how would you like to proceed?

**Comment by matoous** [comment]
Sorry, I quite don't understand, what exactly do you propose?

Matouš Dzivjak
