### ISSUE TITLE
Uncaught ReferenceError: Buffer is not defined

### ISSUE THREAD

**Issue by alexjsdev** [ai/nanoid#212]
I'm seeing an error for when trying to use this in a rollup build in the browser. I'm importing like this: 
`import { nanoid } from 'nanoid'` 

and using it just by setting the result of `nanoid()` to a const, but i'm getting an error in the console, since `Buffer.allocUnsafe` is a node method not available in the browser.  What am i missing?

**Comment by TrySound** [comment]
Do not forget to enable browser field resolving

```
nodeResolve({
  browser: true
})
```

**Comment by ai** [comment]
I am closing this issue because I can’t provide help in Rollup setup
