### ISSUE TITLE
webpack / uglifys incompatibility

### ISSUE THREAD

**Issue by Grabber** [ai/nanoid#213]
webpack
```
uglifyjs-webpack-plugin": "^2.2.0"
uglifyjs-nanoid-plugin": "^2.1.3"
```
```
yarn add nanoid
or
npm install nanoid
```
```
ERROR in bundle.79386546114faba86c4d.js from UglifyJs
Unexpected token: name «urlAlphabet», expected: punc «;» [./node_modules/nanoid/index.browser.js:32,0][bundle.79386546114faba86c4d.js:10854,4]
```

**Comment by ai** [comment]
Seems like your minified do not support ES 2015+. You need to compile Nano ID to ES5 by Babel or user ES2015 compatible minifier like Terser.

**Comment by Grabber** [comment]
@ai, thank you, still not working here... any idea?

## package.json

```
"devDependencies": {
   "@babel/core": "^7.9.0",
   "@babel/preset-env": "^7.9.5",
},
"dependencies": {
   "babel-loader": "^8.1.0",
}
```

## .babelrc
```
{
   "presets": [
      "@babel/env"
   ]
}
```

## webpack.config.js
```
 module: {
   rules: [
      {
         test: /\.m?js$/,
         exclude: /(node_modules)/,
         use: {
            loader: 'babel-loader',
            options: {
               presets: ['@babel/preset-env'],
            },
         },
      },
   ],
},
```

**Comment by ai** [comment]
Because of `exclude: /(node_modules)/`

If you have a webpack, it is better to move to Terser. https://webpack.js.org/plugins/terser-webpack-plugin/

UglifyJS has no maintenance anymore. It is just a question of the time when you will need ES6+ in client-side bundles.

**Comment by TrySound** [comment]
Moreover terser is default with `mode: production`.

**Comment by ai** [comment]
Yeap, you may use UglifyJS because of old webpack
