### ISSUE TITLE
Safe to use in applications managed by pm2 with exec_mode=cluster?

### ISSUE THREAD

**Issue by midnightcodr** [ai/nanoid#214]
From doc I can see that nanoid can guarantee randomness when running in a cluster of  servers due to the use of hardware randomness. I am curious whether this library can be used safely in [pm2's cluster exec_mode](https://pm2.keymetrics.io/docs/usage/cluster-mode/).

**Comment by ai** [comment]
Yeap, it should. Because of the same hardware randomness.

Unique ID in clusters problem happens because of using time-based randomness (like in `Math.random`). If you do not use time-based randomness you free from the problem.
