### ISSUE TITLE
Error: No valid exports main found for '/path/to/nanoid'

### ISSUE THREAD

**Issue by cansin** [ai/nanoid#215]
As initially described at https://github.com/ai/nanoid/issues/206#issuecomment-622967848 , I am getting a `MODULE_NOT_FOUND` error with `node@13.2.0` and `yarn@1.22.4`. 

Here is the repro: https://github.com/cansin/nanoid-module-not-found-repro

And a sample run on my local: 

```bash
cansin@localhost nanoid-repro % node --version
v13.2.0
cansin@localhost nanoid-repro % yarn --version
1.22.4
cansin@localhost nanoid-repro % yarn install
yarn install v1.22.4
[1/5] 🔍  Validating package.json...
[2/5] 🔍  Resolving packages...
[3/5] 🚚  Fetching packages...
[4/5] 🔗  Linking dependencies...
[5/5] 🔨  Building fresh packages...

✨  Done in 0.09s.
cansin@localhost nanoid-repro % node index.js 
internal/modules/cjs/loader.js:614
  throw e;
  ^

Error: No valid exports main found for '/Users/cansin/code/nanoid-reprod/node_modules/nanoid'
    at resolveExportsTarget (internal/modules/cjs/loader.js:611:9)
    at applyExports (internal/modules/cjs/loader.js:492:14)
    at resolveExports (internal/modules/cjs/loader.js:541:12)
    at Function.Module._findPath (internal/modules/cjs/loader.js:643:22)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:941:27)
    at Function.Module._load (internal/modules/cjs/loader.js:847:27)
    at Module.require (internal/modules/cjs/loader.js:1016:19)
    at require (internal/modules/cjs/helpers.js:69:18)
    at Object.<anonymous> (/Users/cansin/code/nanoid-reprod/index.js:1:20)
    at Module._compile (internal/modules/cjs/loader.js:1121:30) {
  code: 'MODULE_NOT_FOUND'
}
```
Thanks.

**Comment by TrySound** [comment]
Now, try to upgrade node.

**Comment by cansin** [comment]
Btw, either upgrading to the latest Node, or even downgrading to LTS `12.16.3` fixes this issue. So perhaps it is not related to the library. But still, you might want to update your engines.node to a valid list.

**Comment by cansin** [comment]
@TrySound see above ^ 😊

**Comment by ai** [comment]
Thanks for the repo. I will take a look today or tomorrow.

**Comment by marcelo-michels** [comment]
Eu estava com o mesmo problema utilizando NodeJS 13. Segui as recomendações de voltar para NodeJS 12 e funcionou. Mas em breve pretendo utilizar com NodeJS 13

**Comment by marcelo-michels** [comment]
I was having the same problem using NodeJS 13. I followed the recommendations to go back to NodeJS 12 and it worked. But soon I intend to use it with NodeJS 13.

**Comment by TrySound** [comment]
@marcelo-michels The latest node 13 should work fine. The problem happens only with early versions.

**Comment by ai** [comment]
@cansin sorry, we do not support old versions of Node.js 13, because they have problems with ESM.

You should update to the latest Node.js 13 version.

**Comment by ai** [comment]
I added note about old Node.js 13 versions to Migration Guide https://github.com/ai/nanoid/releases/tag/3.0.0

**Comment by cansin** [comment]
Sure yeah I already did that. I still suggest you to update your engines.node so that any unsupported node version would complain. Obvs. your call.

**Comment by ai** [comment]
@cansin we support Node.js 10 and 12. Do you have an idea of how to specify `engine`, to avoid old Node.js 13 versions?

**Comment by cansin** [comment]
e.g. Let's say > 13.3 works. I believe something like: 

```json
"engines": {
  "node": "^10 || ^12 || >=13.3"
}
```

would work.

**Comment by cansin** [comment]
i.e. it follows the regular semver rules ( https://docs.npmjs.com/files/package.json#dependencies ).

**Comment by ai** [comment]
@cansin we also need to add `>= 14` to the list.

Do you want to send PR to save your name in the project history?

**Comment by cansin** [comment]
I think `>=13.3` would cover `>=14`. Sure, let me send a PR once I figure out which 13.x versions are failing.

**Comment by ai** [comment]
> I think >=13.3 would cover >=14.

You are right 😅

**Comment by cansin** [comment]
Ok at 13.7 it runs with a warning:

> (node:23723) ExperimentalWarning: Conditional exports is an experimental feature. This feature could change at any time

I will draw the line there.

**Comment by ai** [comment]
The warning is OK

**Comment by cansin** [comment]
@ai any reason why we don't support ^11 ?

**Comment by ai** [comment]
Because 11 is not supported by Node.js https://nodejs.org/en/about/releases/

**Comment by cansin** [comment]
Ah, right. Makes sense
