### ISSUE TITLE
Can't Find variable self React Native

### ISSUE THREAD

**Issue by danielreptar** [ai/nanoid#217]
Hello, i use the library to generate nanoid, but somtimes give this error. 
![image](https://user-images.githubusercontent.com/50254591/81343736-271fe400-907b-11ea-8460-47a67fa57053.png)

this is my code.
imports
![imports](https://user-images.githubusercontent.com/50254591/81344469-6c90e100-907c-11ea-8126-260230719f6b.png)

Package.json
![package-json](https://user-images.githubusercontent.com/50254591/81344494-76b2df80-907c-11ea-8223-162242e764ab.png)

and this is the part of code where i use the nanoid
![nanoid](https://user-images.githubusercontent.com/50254591/81344503-79153980-907c-11ea-987f-d5efb5f01303.png)

**Comment by danielreptar** [comment]
![self](https://user-images.githubusercontent.com/50254591/81351418-e67b9700-9089-11ea-8beb-a964a0767e61.png)

**Comment by ai** [comment]
@danielreptar thanks for the report.

Can you try this commit? https://github.com/ai/nanoid/commit/35ea2907d158f7aa5956ee1fdb4155d11bf251fa

```sh
npm uninstall nanoid
npm install nanoid@ai/nanoid
```

**Comment by danielreptar** [comment]
now it gives me this error
![image](https://user-images.githubusercontent.com/50254591/81415396-05237180-910e-11ea-8dd5-246fd36618d6.png)


I already put in my index.js
`import "react-native-get-random-values";`

**Comment by ai** [comment]
The error came from `react-native-get-random-values`. You need to open an issue there.

**Comment by ai** [comment]
I released `self` fix in 3.1.6
