### ISSUE TITLE
Fail to load module

### ISSUE THREAD

**Issue by jjasonclark** [ai/nanoid#226]
I'm getting an error while loading 3.1.8 or greater on Node 12.14.1.

```
ERROR	Uncaught Exception 	{
"errorType":"Runtime.ImportModuleError","errorMessage":"Error: Cannot find module './url-alphabet/index.cjs'
Require stack:
- /var/task/node_modules/nanoid/index.cjs
- **omit**
```

Also the file looks like it might have failed a build step. https://www.runpkg.com/?nanoid@3.1.10/url-alphabet/index.cjs

```javascript
// This alphabet uses `A-Za-z0-9_-` symbols. The genetic algorithm helped
// optimize the gzip compression for this alphabet.
let urlAlphabet =
  'ModuleSymbhasOwnPr-0123456789ABCDEFGHNRVfgctiUvz_KqYTJkLxpZXIjQW'
module.exports = { urlAlphabet }
```

**Comment by ai** [comment]
> I'm getting an error while loading 3.1.8 or greater on Node 12.14.1.

Do you use bundler like webpack? Or it is Node.js program?

How do you import Nano ID?

> Also the file looks like it might have failed a build step

Why this file looks like failed?

Can you also try to reinstall dependencies? `rm -R node_modules && npm i`

**Comment by jjasonclark** [comment]
You are correct. It was a bundling issue. I was using Serverless-Jetpack to package up a lambda that used NanoId to create Ids for Dynamodb tables. Jetpack was not including the `cjs` files. A PR was created for https://github.com/FormidableLabs/trace-deps/pull/31. I've checked it out and it does include the correct file without manual changes to the included files.

**Comment by ai** [comment]
Seems like we need to wait for this PR. There is nothing I can fix here expect suggest you to move to another bundler.

**Comment by jjasonclark** [comment]
Yes, agreed. There is nothing to fix or change in nanoid. I would suggest closing this issue since it doesn't apply.
