### ISSUE TITLE
customAlphabet in nanoid/async/index.browser is not actually async

### ISSUE THREAD

**Issue by LoneRifle** [ai/nanoid#228]
Visual comparison of  `customAlphabet()` between `/index.browser.js` and `/async/index.browser.js` suggests that the async version is really synchronous. This should either be changed to at least return a Promise, or documented.

**Comment by ai** [comment]
Yeap, it is sync, since browser do not have async API. We have it just for compatibility.

I like the idea to document it.

Can you send PR?

**Comment by LoneRifle** [comment]
I would love to, after clarifying the following: 

`generate()` in v2 was available in async form (by delegating the async to format()) for browsers, and most major browsers have at least some support for Promises.  Further, `nanoid()` and `random()` in `async/index.browser` make at least one use of `Promise.resolve()`.

When you say that browsers do not have async API, do you mean to say that we have to account for legacy browsers too?
