### ISSUE TITLE
Nanoid in python

### ISSUE THREAD

**Issue by puyuan** [ai/nanoid#23]
@ai  I have ported nanoid in python while experimenting with it in my own project. 

You can check my work here:

https://github.com/puyuan/py-nanoid

TODOs: 
I haven't included your simpler 64 alphabet algorithm yet (will do so when I have time), currently its based on the general algorithm. 

If you find it ok, perhaps you can help me link the python version.

**Comment by ai** [comment]
Looks good. Feel free to send PR with your project
