### ISSUE TITLE
tsc doesn't seem to use the async cjs file when compiling

### ISSUE THREAD

**Issue by dilizarov** [ai/nanoid#235]
I'm using this library in my NestJS project (https://docs.nestjs.com/).

Whenever I run `npm run start:dev`, I believe it compiles via tsc.

The error I get is:

```
/project/node_modules/nanoid/async/index.js:1
import crypto from 'crypto'
       ^^^^^^

SyntaxError: Unexpected identifier
    at Module._compile (internal/modules/cjs/loader.js:872:18)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:947:10)
    at Module.load (internal/modules/cjs/loader.js:790:32)
    at Function.Module._load (internal/modules/cjs/loader.js:703:12)
    at Module.require (internal/modules/cjs/loader.js:830:19)
    at require (internal/modules/cjs/helpers.js:68:18)
    at Object.<anonymous> (/project/dist/utils/generateId.js:4:17)
    at Module._compile (internal/modules/cjs/loader.js:936:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:947:10)
    at Module.load (internal/modules/cjs/loader.js:790:32)
```

The only place where I'm using nanoid, I import it as such:

`import { customAlphabet } from "nanoid/async";`

This is my tsconfig file:

```
{
  "compilerOptions": {
    "module": "commonjs",
    "esModuleInterop": true,
    "declaration": true,
    "removeComments": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "target": "es2017",
    "sourceMap": true,
    "outDir": "./dist",
    "baseUrl": "./",
    "incremental": true,
    "resolveJsonModule": true,
    "paths": {
      "*": ["node_modules/*", "src/*"]
    }
  }
}
```

When I looked into node_modules, indeed `nanoid/async/index.js:1` was the import line, but I also saw the `nanoid/async/index.cjs` file and assumed that would be the one used due to my compilerOptions using `"commonjs"`.

My node version is `v12.10.0`, but I don't know if that matters.

**Comment by ai** [comment]
Nope, the problem iis that yo do not tell TypeSCript, yhat you are creating module for Node.js.

TypeScript parsed `import` (there is not syntax error), but was not able to import `crypto`. `crypto` is a standart Node.js module. So very likely TS just can’t find any `crypto` module because of lack of some Node.js enable option.

Can I ask you to check docs and write a cmment if it will help. I will add it to TS section in NanoID docs.

**Comment by dilizarov** [comment]
@ai It doesn't have anything to do with Crypto. It has to do with the file being written in esm. In order for my project to understand the ECMAScript module loading in that file, I used this cool library that handles everything behind the scenes: https://github.com/standard-things/esm

By changing my command from `nest start --watch` to `nest start --watch -e "node -r esm"`, I was able to get this working.

Node.js does have experimental support for ECMAScript modules, but unless one wants to deal with it by hand, simply using that library is the easiest way to deal with it.

**Comment by ai** [comment]
Seems like `esm` doesn’t have `crypto` module.

If you don’t need really random IDs, you can use `nanoid/non-secure`.

If you need a random ID, we need a module for hardware random generator. Do you know how to load it in `esm`?

**Comment by ai** [comment]
Off-topic: why do you use `esm`? Node.js 14 has a stable ESM support (not experimental). It is good and support all Node.js modules like `crypto`. Works great.

**Comment by ZQun** [comment]
@ai hello, I use nanoid in node ts, and it always prompts 'nanoid is not a function'. I tried several methods to introduce it, but it didn’t work.

node version: v14.15.0 and v12.16.1
```ts
// The first
import { nanoid } from 'nanoid'
let id: string = nanoid()

// The second
import * as nanoid from 'nanoid'
let id: string = nanoid.nanoid()

// The third
const { nanoid } = require('nanoid')
let id: string = nanoid()
```
```json
// tsconfig.json
{
  "compileOnSave": true,
  "compilerOptions": {
    "target": "ES2018",
    "module": "commonjs",
    "moduleResolution": "node",
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "inlineSourceMap":true,
    "noImplicitThis": true,
    "noUnusedLocals": false,
    "stripInternal": true,
    "pretty": true,
    "declaration": true,
    "outDir": "dist"
  },
  "exclude": [
    "dist",
    "node_modules",
    "test"
  ]
}
```

**Comment by ai** [comment]
@ZQun be sure that you are using the latest `nanoid` 3.1.16 and removed `@types/nanoid`

**Comment by ZQun** [comment]
@ai 
Sorry, I used nanoid version 3.1.16 for the first time, but an error will be reported when I execute npm run dev：`Must use import to load ES Module`  `***/node_modules/nanoid/async/index.browser.js` ` require() of ES modules is not supported.`，Later, nanoid 2.1.11 was installed and there was no error in the operating environment, but random id could not be generated.
```
rm -rf node_modules package-lock.json
npm i
npm run dev
```

**Comment by ai** [comment]
@ZQun open a separate issue with full details. Your current code, your build tool, bundler if you use some, full error message.

**Comment by ZQun** [comment]
> @ZQun open a separate issue with full details. Your current code, your build tool, bundler if you use some, full error message.

@ai 
Thank you for your answer, the problem has been solved, because the `nanoid` is used in the components in the framework, now the developer has ignored the repeated dependencies and can be used normally

**Comment by ai** [comment]
Seems like this issue was solved
