### ISSUE TITLE
Importing in browser throws on "process.env.NODE_ENV" under development

### ISSUE THREAD

**Issue by michaelrommel** [ai/nanoid#236]
Hi,

the comment in index.browser.js correctly states that rollup will remove the block in production, but during development, it still is there and crashing the browser.

Using nanoid 3.1.12 and rollup 2.26.4 in a svelte environment.

Is there any documentation, how to import and use nanoid in this scenario in development?

Thanks a lot,

  Michael.

NB: Problem was also mentioned in: https://github.com/ai/nanoid/issues/127#issuecomment-529073587 but even now that ESM module support was announced, this is a problem.

**Comment by ai** [comment]
You need to use `@rollup/plugin-replace` or `rollup-plugin-inject-process-env` to replace `process.env.NODE_ENV` to string value during the build.

Can you try both of this solution, find the simplest one, and send PR to docs? Sorry, I am mostly a Webpack/Parcel user and need help with Rollup.

**Comment by TrySound** [comment]
FYI `@rollup/plugin-replace` is an official plugin to do this.

**Comment by ai** [comment]
@TrySound should we pass `process.env.NODE_ENV` as a key to `@rollup/plugin-replace` options? I didn’t find an API for this popular case in docs.

**Comment by TrySound** [comment]
Hm.. you are right. Need to tweak docs.
```js
replace({
  'process.env.NODE_ENV': JSON.stringify('production') // JSON.stringify('development')
})
```

**Comment by ai** [comment]
I improved docs deae871
