### ISSUE TITLE
Deno support

### ISSUE THREAD

**Issue by jsejcksn** [ai/nanoid#246]
Related #237

I think the Deno community would benefit from this module being released in ESM format.

Right now, it appears that there is a minified ES module: [`nanoid.js`](https://github.com/ai/nanoid/blob/master/nanoid.js)

Has it been discussed to release a TypeScript source ES module?

**Comment by ai** [comment]
Should we copy the PostCSS way for Deno.

We can add `nanoid-deno` repo where we will rebuild Nano ID sources and publish it to `deno.land/x`. See [`postcss/postcss-deno`](https://github.com/postcss/postcss-deno).

**Comment by jsejcksn** [comment]
Hi @ai, thanks for responding.

I'm not familiar with that repo, but after glancing at some of the source, it appears to be using an automated codemod; that's not what I was asking about. I'll try to rephrase my question:

Has it been discussed to rewrite the _browser_ source in native TypeScript, and then compile the (minified) JavaScript module from that?

I referenced #237 because it seems like there's already discussion about a native ES module rewrite. It looks like the project already includes TS declaration files, so I'm wondering if there's something preventing writing the source in TypeScript.

**Comment by ai** [comment]
> Has it been discussed to rewrite the browser source in native TypeScript, and then compile the (minified) JavaScript module from that?

Nope. I against any build steps in open source libraries.

I like to use to test version from GitHub by installing `npm install nanoid@ai/nanoid`. With TypeScript it will be imporssible.

**Comment by jsejcksn** [comment]
> Nope. I against any build steps in open source libraries.

How is https://github.com/ai/nanoid/blob/master/nanoid.js produced?

Surely it's not written by a human...

**Comment by ai** [comment]
`nanoid.js` is the only exception and I do not want to add more exceptions
