### ISSUE TITLE
So um.. How do you use this on the client side in an html page? what is import { nanoid } from 'nanoid'? :)

### ISSUE THREAD

**Issue by tdbe** [ai/nanoid#247]
It would be very nice to just have a clean simple pure client side html + plain old javascript way to use nanoid, showcased in readme.md.

**Comment by ai** [comment]
I am afraid that using Nano ID from a third-party CDN (the only way to use Nano ID without npm) is a bad practice since it affects performance.

What is your use case?

**Comment by tdbe** [comment]
My use case is a client side tool, or a videogame, where I need unique ids for nothing sensitive or important and performance of generating one of these is not important.

**Comment by tdbe** [comment]
And really, from the docs I can see, UX wise, I can't understand *how* nanoid JS is meant to be used. I'm not an es6 js programmer, so I don't even know precisely what "import { nanoid } from 'nanoid'" is; to put it bluntly, I just imported and pasted code and it told me:

`Uncaught SyntaxError: Cannot use import statement outside a module`

I'm sure to you it's obvious why, but for the internet it might not necessarily be the case.

**Comment by ai** [comment]
> I can't understand how nanoid JS is meant to be used. 

You need to install npm and then call `npm i nanoid`.

Then you need to use a JS bundler like webpack. I recommend to start from Parcel since it has a better DX:

```sh
npm i parcel
npx parcel serve index.html --open
```

In `index.html` you need to write something like:

```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <script>
      import { nanoid } from 'nanoid'
      document.body.innerText = nanoid()
    </script>
  </head>
  <body>
  </body>
</html>
```

**Comment by ai** [comment]
If the advice above will work for you, I will add it to the docs

**Comment by tdbe** [comment]
This is a very nice explanation. You should. Now I basically understood that: ain't no way I'm gonna do all that - I just want short uuids that work in plain old javascript; I'll look elsewhere thank you!

**Comment by TrySound** [comment]
@tdbe Here, you can use this url for home project. Though keep in mind unpkg service may be unavailable sometimes.
https://unpkg.com/browse/nanoid@3.1.18/index.dev.js

```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <script type="module">
      import { nanoid } from 'https://unpkg.com/browse/nanoid@3.1.18/index.dev.js'
      document.body.innerText = nanoid()
    </script>
  </head>
  <body>
  </body>
</html>
```
