### ISSUE TITLE
Ruby implementation

### ISSUE THREAD

**Issue by radeno** [ai/nanoid#25]
Hello,
i like this random generator.

In our-project we need some cluster-safe generator uniq, short and human friendly. We have tried Hashids, but it doesn't fulfil our expectations.

Our backend is written in Ruby language so i reimplement your original algorithm in ruby:
https://github.com/radeno/nanoid.rb

**Comment by ai** [comment]
Great! I checked the source and everything looks good (we uses Ruby as well).

Please send PR to `README.md` with link to your project
