### ISSUE TITLE
React example just seems incorrect

### ISSUE THREAD

**Issue by FokinAleksandr** [ai/nanoid#251]
There seems to be no reason to specify a key inside a component and not when you React.createElement link.
So I guess there's basically no reason to use nanoid for React keys
https://reactjs.org/docs/lists-and-keys.html#extracting-components-with-keys
https://github.com/ai/nanoid#react

**Comment by ai** [comment]
Yeap, you are right. Can use send PR?

**Comment by FokinAleksandr** [comment]
yep sure

**Comment by ai** [comment]
Fixed by https://github.com/ai/nanoid/pull/252
