### ISSUE TITLE
Why not use nanoid to generate stable ids

### ISSUE THREAD

**Issue by praveeno** [ai/nanoid#257]
![image](https://user-images.githubusercontent.com/19618730/103398986-0570f100-4b65-11eb-8196-5cbcdc354cec.png)

not sure on this, but instead of showing [antipattern](https://medium.com/@robinpokorny/index-as-a-key-is-an-anti-pattern-e0349aece318), as a possible solution, why don't we purpose that nanoid can be use to generate stable id, before rendering
```js
// async fetch
todos.forEach((todo) => todo.id = nanoid());
// ....

// render with stable id as key.
``` 
this is kind of obvious, but beginners (including me :)) will either use antipattern or get confuse on this. 

let me know you thoughts on this.
Thanks

**Comment by ai** [comment]
We can change the example. Please, send PR. But note that good example:

1. Should not change objects. So we need, for instance, to convert `obj` to `[id, obj]`
2. Run ID generation only once by something like `useLayoutEffect` or something similar.
