### ISSUE TITLE
nanoid/generate is not defined

### ISSUE THREAD

**Issue by Tanjersal** [ai/nanoid#258]
First of all, thank you for such a wonderful library, once I discovered it I had to drop "shortId".

Now, as I set up to use your library following your nanoId collision calculator web page, I am unable to use the file "nanoid/generate" to generate my custom ids as the website I cited advises to do. 

Is there something I am missing or the "generate" file no longer exists with the current version?

Thank you, 

Collision calculator site: https://zelark.github.io/nano-id-cc/

**Comment by Tanjersal** [comment]
My bad, just found that a customAlphabet function was provided to generate custom ids. Thank you

**Comment by anshulsahni** [comment]
is `nanoid/generate` thing deprecated?

**Comment by Tanjersal** [comment]
@anshulsahni Maybe! I was able to use customAlphabet to generate custom id like below.
const nanoId = require('nanoId')
let ids = nanoid.customAlphabet('abcdef', 5); 
ids() //generates your ids

**Comment by TrySound** [comment]
@anshulsahni It was removed in [nanoid v3](https://github.com/ai/nanoid/blob/main/CHANGELOG.md#30)

**Comment by anshulsahni** [comment]
I guess the confusion was due to outdated demo code in nanoid collision calculator, fixed it here in this PR 👉 https://github.com/zelark/nano-id-cc/pull/28

**Comment by zelark** [comment]
Fixed.

**Comment by ai** [comment]
I sent a small fix https://github.com/zelark/nano-id-cc/pull/29
