### ISSUE TITLE
error on usage

### ISSUE THREAD

**Issue by chovy** [ai/nanoid#259]
`briskreader-api | SyntaxError: The requested module 'file:///usr/src/app/node_modules/nanoid/index.js' does not provide an export named 'nanoid'`

```
import { nanoid } from 'nanoid';



const ReadSchema = new Schema(
  {
    title: { type: String, required: true },
    url: { type: String, required: true, unique: true },
    shortId: {
      type: String,
      required: true,
      unique: true,
      index: true,
      default: () => nanoid(11),
    },
```

**Comment by chovy** [comment]
getting this on node lts

**Comment by TrySound** [comment]
Which version of nanoid do you use? And which exactly node version?

**Comment by chovy** [comment]
my bad. i hadn't ran `npm i` yet on deploy.
