### ISSUE TITLE
Unable to import in nodejs Typescript

### ISSUE THREAD

**Issue by GarrickBee** [ai/nanoid#261]
Error Throw while trying to compile tyepscript

uncaughtException: Error [ERR_REQUIRE_ESM]: Must use import to load ES Module
require() of ES modules is not supported.
... is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": ...

**Comment by ai** [comment]
I can’t help with TypeScript configuration.

Very likely that you should try to change `module` in `tsconfig.json`.
