### ISSUE TITLE
Does this library not support regex for building custom alphabet??

### ISSUE THREAD

**Issue by MathiasHaudgaard** [ai/nanoid#262]
Not really sure if I'm not able to find that feature since it should be quite obvious that it should be supported instead of writing a big string of all the characters that you want in your alphabet. Can someone help me out? :shipit:

**Comment by ai** [comment]
Nope, there is not such support.

You can add it manually by something like:

```js
// It will be a little slow, better to cache alphabet somewhere
function regexpToAlphabet (regexp) {
  let alphabet = ''
  let symbol = String.fromCharCode(i)
  for (let i = 0; i < 127; i++) { // Will work with simple ASCII symbols. SHould be more complicated for Unicode.
    if (regexp.test(symbol)) {
      alphabet += symbol
    }
  }
  return alphabet
}
```
