### ISSUE TITLE
Screw you for your dependency mess

### ISSUE THREAD

**Issue by craigmiller160** [ai/nanoid#264]
Seriously, some of us don't want to jump through a ton of webpack hoops just to use a library. You're publicly available, thank you for making my life more complicated than it needs to be. I've got enough BS to deal with on a daily basis.

**Comment by ai** [comment]
Nano ID has **0** dependencies.

Maybe you missed this library with another tool?

**Comment by leo-vannini-granicus** [comment]
@craigmiller160 grow up.
