### ISSUE TITLE
3.1.22 Breaks PostCSS 8.2.8

### ISSUE THREAD

**Issue by bdkjones** [ai/nanoid#267]
When I run `npm install nanoid`, the installed package is version `3.1.22`. This produces an error when I run PostCSS 8.2.8:

Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: node_modules/nanoid/non-secure/index.js
require() of ES modules is not supported.
require() of node_modules/nanoid/non-secure/index.js from node_modules/postcss/lib/input.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from node_modules/nanoid/non-secure/package.json.

## Notes:
1. This issue exists even when I do not install `nanoid` explicitly, but rather allow npm to install whatever version is required by PostCSS 8.2.8

2. Deleting the `type: module` line from the package.json file yields a new error about an `export` statement not being recognized.

3. I rolled `nanoid` back to a known-good version: `3.1.20` and PostCSS now runs correctly again, with no modifications to anything in `nanoid`.

3. I am using Node 15.11.0

**Comment by ai** [comment]
What is the minimum code to get an error? Do you just require `postcss`?

Do you use ESM in your application?

**Comment by bdkjones** [comment]
Oh, wow, this one was nuts. The issue is a post-install script that simply alphabetizes the entries in a `package.json` file. That is, it takes property names and puts them in alphabetical order (obviously it doesn't change the order of items in an array). 

In this case, that means the `exports` fields go from this: 

```
exports {
    [...]
    "./non-secure": {
         "import": "./non-secure/index.js",
         "require": "./non-secure/index.cjs",
         "default": "./non-secure/index.js"
    },
    [...]
}
```

To this:

```
exports {
    [...]
    "./non-secure": {
         "default": "./non-secure/index.js"
         "import": "./non-secure/index.js",
         "require": "./non-secure/index.cjs",
    },
    [...]
}
```

And because `default` now appears before `require`, node is grabbing the `*.js` file instead of the `*.cjs` file, producing the error in my original post.

That MUST be some sort of oversight in Node, right? Objects in json are **by definition** unordered: https://www.json.org/json-en.html

This is either an oversight or Node is violating the JSON spec. The reason that `nanoid` 3.1.20 works just fine is that you added the `default` entries in the last update or two.


## Node Docs
Here's the documentation on subpath imports in the `exports` field for package.json files: https://nodejs.org/api/packages.html#packages_subpath_imports

Note that it makes ZERO mention of any ordering requirements or the precedence of entries in the `exports` field.

**Comment by bdkjones** [comment]
Note: the reason I have this post-install script is that I have to ship a billion node packages in my app and if I compress the JSON (remove whitespace, remove unneeded fields such as `keywords`, etc) for ALL of them, I can knock 15-20 mb off the total size. 

That script, in addition to compressing, alphabetizes property names in objects. Even if it didn't alphabetize them, it would not retain the same order because...objects are unordered in JSON.

**Comment by bdkjones** [comment]
Well, the node team knows damn well they're violating the JSON spec:

<img width="874" alt="Screen Shot 2021-03-16 at 23 05 11" src="https://user-images.githubusercontent.com/926566/111422797-80e63700-86ac-11eb-82a5-ea5e5393dd61.png">

I Guess node is just too large to care about language specs any longer; they ARE the language now. I'll just have to update my script to work around their dumb choices.

**Comment by ai** [comment]
🤯
