### ISSUE TITLE
Vite support

### ISSUE THREAD

**Issue by dkzlv** [ai/nanoid#269]
I use Svelte Kit, it uses Vite. And I have problems with nanoid, because [`index.browser.js` has checks](https://github.com/ai/nanoid/blob/main/index.browser.js#L6) on `crypto` being available on `global` namespace.

Even though the library's functions are not called during SSR, [the module still gets imported in the Node](https://github.com/sveltejs/kit/issues/779#issuecomment-810432296). So this is what you would get in the new default Svelte Kit project if you just import nanoid in a component and do nothing with it:

```
11:17:09 AM [vite] Error when evaluating SSR module /node_modules/nanoid/index.dev.js:
Error: Your browser does not have secure random generator. If you don’t need unpredictable IDs, you can use nanoid/non-secure.
    at /node_modules/nanoid/index.dev.js:28:11
    at instantiateModule (../node_modules/vite/dist/node/chunks/dep-0776dd57.js:68919:166) (x163)
```

I propose to move the check inside the functions.

**Comment by TrySound** [comment]
SSR should use node version https://github.com/ai/nanoid/blob/main/index.js. Might be a bug in sveltekit.

**Comment by ai** [comment]
We have explicit instructions in `package.json → exports` that only browser should use `index.browser.js`.

Adding a browser check-in function will bloat the library multiple times.

Seems like Vite has an issue with SSR. Can you create an issue there?

**Comment by ai** [comment]
I tested `nanoid` in fresh Vite and everything is working correctly
