### ISSUE TITLE
[Question] What is the collision probability with a reduced alphabet size and/or reduced ID length?

### ISSUE THREAD

**Issue by nvpsswaroop** [ai/nanoid#27]
@ai 
Currently nanoid by default uses `A-Za-z0-9_~` for its alphabet. Now if we reduce the alphabet to human readable characters, say, `A-Z, 0-9`, excluding the commonly confused `01OI`, what would be the impact on collision probability in nanoid?

And, if we reduce the ID length from 22 symbols to say 10 symbols, how would the uniqueness be effected in a single processor and/or multi-processor scenario?

**Comment by ai** [comment]
Where exactly you use this ID?

**Comment by nvpsswaroop** [comment]
@ai Each user in our system requires a unique human readable code of reasonable length which they type in from time to time for an information retrieval. At the moment, we are using shortid to do this and its generating codes with around 9 symbols. But since shortid uses an alphabet with 64 symbols, we are unable to avoid special characters such as `$, #, @` from our alphabet which makes it harder to for users to type the shortid codes.

**Comment by ai** [comment]
How many users you have right now and will have in next few years (optimisticly)?

(I ask you this question, because it is always better to have real case to find best solution)

**Comment by nvpsswaroop** [comment]
At the moment, we have less than 10k and in near future it may hit something around 100k. But on a longer term it might be around 1million under the best possible scenario

**Comment by ai** [comment]
32 symbols (5 random bits), 10 symbols (50 random bits in each ID). For 1M users collision probability is **0.00044**.

I used this calculator:
http://everydayinternetstuff.com/2015/04/hash-collision-probability-calculator/

If ID length is critical for you, you can start from 10 symbols and increase ID length when you will have 100K users.

**Comment by iamjochem** [comment]
hi @ai, I was wondering how is  the `5 random bits (per symbol)` for `32 symbols` determined/calculated?

**Comment by ai** [comment]
@iamjochem just calculate `n` in `2**n=32` (how many `2` you need to multiple between each other to get `32`, `32=2*2*2*2*`).

**Comment by iamjochem** [comment]
ah I see, thanks.

am I correct in thinking that any "alphabet" with between 32 & 63 chars would result in 5bit of randomness per char of output?

**Comment by ai** [comment]
@iamjochem in this case math is more complex and I am not so good in it 😅.
