### ISSUE TITLE
UMD distro of nanoid

### ISSUE THREAD

**Issue by atorres-eqrx** [ai/nanoid#270]
### Context:
---
I'm trying to generating some client-side ids in our internal facing application using our low-code frontend tool, Retool.

Retool has [support for loading npm modules](https://docs.retool.com/docs/custom-js-code#custom-javascript-libraries--npm-modules). I've tried following the instructions in the Retool docs by including a library published to [cdnjs](https://cdnjs.com/libraries/nanoid).  

The issue i'm finding is that the browser variants published to cdnjs use the `import` keyword.

You can see an example here (_Source copied for convenience_ )

https://cdnjs.cloudflare.com/ajax/libs/nanoid/3.1.22/index.browser.min.js

```javascript
import{urlAlphabet}from"./url-alphabet/index.js";if("production"!==process.env.NODE_ENV){if("undefined"!=typeof navigator&&"ReactNative"===navigator.product&&"undefined"==typeof crypto)throw new Error("React Native does not have a built-in secure random generator. If you don’t need unpredictable IDs use `nanoid/non-secure`. For secure IDs, import `react-native-get-random-values` before Nano ID.");if("undefined"!=typeof msCrypto&&"undefined"==typeof crypto)throw new Error("Import file with `if (!window.crypto) window.crypto = window.msCrypto` before importing Nano ID to fix IE 11 support");if("undefined"==typeof crypto)throw new Error("Your browser does not have secure random generator. If you don’t need unpredictable IDs, you can use nanoid/non-secure.")}let random=e=>crypto.getRandomValues(new Uint8Array(e)),customRandom=(e,o,t)=>{let r=(2<<Math.log(e.length-1)/Math.LN2)-1,n=-~(1.6*r*o/e.length);return()=>{let a="";for(;;){let i=t(n),d=n;for(;d--;)if((a+=e[i[d]&r]||"").length===o)return a}}},customAlphabet=(e,o)=>customRandom(e,o,random),nanoid=(e=21)=>{let o="",t=crypto.getRandomValues(new Uint8Array(e));for(;e--;){let r=63&t[e];o+=r<36?r.toString(36):r<62?(r-26).toString(36).toUpperCase():r<63?"_":"-"}return o};export{nanoid,customAlphabet,customRandom,urlAlphabet,random};
```

The "browser" package also currently checks `process.env.NODE_ENV`.

### Request:
---
Is it possible to publish a CDN package which can be imported into Retool that adheres to these requirements?

![image](https://user-images.githubusercontent.com/72038775/114445194-cad41700-9b9d-11eb-9c58-3ba4bff68562.png)

**Comment by ai** [comment]
Try the `nanoid.js` file to the project root. For instance, from jsdelivr.net:

```js
import { nanoid } from 'https://cdn.jsdelivr.net/npm/nanoid/nanoid.js'
```

**Comment by am17torres** [comment]
> Try the `nanoid.js` file to the project root. For instance, from jsdelivr.net:
> 
> 
> 
> ```js
> 
> import { nanoid } from 'https://cdn.jsdelivr.net/npm/nanoid/nanoid.js'
> 
> ```

Unfortunately Retool chokes on the `import` keyword. I need nanoid attached to `window` in order for the browser to use it.

**Comment by ai** [comment]
I personally think, that UMD is very outdated way and I do not see a rational reasons to use UMD in new project.

This is why I do not want to spend time on support this way. You can create a small script which will re-pack Nano ID for your legacy project.

If you publish it open source, I will add link in Nano ID docs.

**Comment by kocoten1992** [comment]
Hello @ai, there are many reason for UMD style - mostly for speed, the ability to quickly test out idea, to shoot and forget:
- npm is slow, typical it take 10-30s to install (this add up for each developer, or each time CI/CD run).
- CDN are great, if we all using webpack, we need to host our final dense concentrate js file, where as using CDN a few extra http requests is going to be cached by browser anyway.
- When using in internal/admin site, there is not a lot of reason to care about security (pleasing npm asking about security update is also a pain).

Could we revert decision drop  support for UMD style ?

**Comment by ai** [comment]
@kocoten1992 can you use npm-to-ESM CDNs for this task? 

```js
import { nanoid } from 'https://unpkg.com/nanoid@3.1.23/nanoid.js'
```

**Comment by kocoten1992** [comment]
Hi @ai , what I mean is using directly in the browser for faster development speed (without having to go through npm or js processor), like this old timer jquery:

```html
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
```

Browser choke on `import` keyword
```js
import { nanoid } from 'https://unpkg.com/nanoid@3.1.23/nanoid.js'
// Uncaught SyntaxError: Cannot use import statement outside a module
```

The idea was after application have enough userbase, it make more sense to optimize for npm and many stuff later..

**Comment by ai** [comment]
> Browser choke on import keyword

```html
<script type="module">
import { nanoid } from 'https://unpkg.com/nanoid@3.1.23/nanoid.js'
</script>
```

**Comment by kocoten1992** [comment]
thank you very much, TIL that :heart:
