### ISSUE TITLE
Exports breaks for CJS requires on JSPM

### ISSUE THREAD

**Issue by guybedford** [ai/nanoid#271]
ipfs-utils@6.0.7 includes `require('nanoid')`, and assumes this to be a function.

When running on JSPM, the "exports" field defines that in the browser nanoid should be loaded from `index.prod.js` which exports an interface looking like `{ nanoid, ... }` which does not export a default export as a function for require to use.

See the example [here](https://jspm.org/sandbox#H4sIAAAAAAAAA31UbU/bMBD+zq84si+wkaRl0wYlrXgVAhrEllWsH018JR6J7dluS5j233dx2o4imJTEsu/luXv8XJJNrnJXa4TCVeVgI1kuyPhgAyCp0DHIC2Ysun4wdZNwL/AGJ1yJg5H0K0/idr8KkazCfjATONfKuAByJR1KSjEX3BV9jjORY+g3OyCkcIKVoc1Zif0uASRxW0Fyp3jts26GIZxlkCo+LRGyQlS2BxdVkx0qpi1oVdYTUZYwUQYq72bhzqi5RWNhLlyhpg7Eswg71X6zxSgKH3PUDk4KoyqEvf0P2xCGHtnmRpCF2VrmYE3eDwrntO3F8T2LflpdRULFUlc9tGGLG9qmvMNO1KUn5sK6+IUtqoSk2GCQxG36BmnRJi0Al9lNCuco0TBH/SwaTZn21jMuHIy+DXuwKmXpuqro3Wj3+n58fvxwmnZMnT1dZqNuUZ88Xlztj90wl+nVj/G883TzNd3PZ8MHczvsyOshP76us/nJUTru/FKf7NER4a3z0KilH7Q8Eo1eDb99VYtDG/QWB82Rnthw6kRpY6IudljpkAtDLm+x+C/i8HPUib6sxUWLC2248xB/dlpomyuNa8ivpH9mJgfJpBL8P5W0Docfo260242F5PgYaaP4CpzgN5bf5n15mWuMtdfv6YKlDN+TqqBpeNT0m5n8O/V5KgxMSIVvk3fQ5geIY7g1wiHpWciF6GnUOI0zGtwBUg4BMLCoGakDgQYE/SzQYUA5A2DOGXE3JZuS4ApcZmlrjzwMDa9VJUalut96pdrtg7Xek7gdWpph/zP5C/+LMmFkBAAA).

I'd suggest changing the browser exports to possibly have separate require and import variants to ensure the interfaces match up for both CommonJS and ESM consumers.

**Comment by guybedford** [comment]
I should clarify, this is for nanoid 3.1.21.

**Comment by ai** [comment]
> ipfs-utils@6.0.7 includes require('nanoid'), and assumes this to be a function.

Seems like `ipfs-utils` uses old Nano ID 2.x.

Nano ID 3.x has no default export in all files (in both CJS/ESM).

Seems like the problem with `package.json` version requirements, not with dual CJS/ESM.

**Comment by guybedford** [comment]
Thanks for the quick response! `ipfs-utils` definitely does have a dependency on `nanoid@^3.1.20`. That it's using `3.1.21` and not `3.1.22` was an issue though, but even on `3.1.22` I'm still seeing the same issue.

I'm pretty sure this is the standard CJS / ESM interface mismatch issue (basically _the_ interop issue).

**Comment by ai** [comment]
> I'm pretty sure this is the standard CJS / ESM interface mismatch issue

Here is CJS export https://github.com/ai/nanoid/blob/main/index.js#L80

As you see it doesn’t export function. It exports an object with `nanoid` key with a function.

> Thanks for the quick response! ipfs-utils definitely does have a dependency on nanoid@^3.1.20. 

Can you show `ipfs-utils` source line with nanoid usage?

**Comment by guybedford** [comment]
The usage is at https://unpkg.com/ipfs-utils@6.0.7/src/temp-dir.browser.js.

It seems like it is in fact using that exact export, so this is my bug after all!
