### ISSUE TITLE
The length of the generated characters is not the defined size

### ISSUE THREAD

**Issue by haishangfeng** [ai/nanoid#272]
nodejs

```
import { customAlphabet } from 'nanoid';
const v_code = customAlphabet ('1234567890', 4);
```

I used the above code to generate a random number with a length of 4 digits,
But sometimes the random number generated is only 3 digits, 
and the probability of this happening is very high.

**Comment by ai** [comment]
Do you convert v_code to Number type (for instance with `parseInt`)?

Maybe codes with leading `0` is converted to 3-digits number?

```js
const id = `0123`
parseInt(id) //=> 123
```

**Comment by haishangfeng** [comment]
no,  I quote directly。


 const random4 = Math.floor(Math.random()*(8999))+1000;
So how to use customAlphabet to generate four fixed random numbers?  such as  above code

**Comment by ai** [comment]
> So how to use customAlphabet to generate four fixed random numbers?

```js
let first = customAlphabet ('123456789', 1)
let tail = customAlphabet ('1234567890', 3)

function getCode4 () {
  return first() + tail()
}
```

**Comment by haishangfeng** [comment]
Good job,tks very much.
