### ISSUE TITLE
CLI Improvements

### ISSUE THREAD

**Issue by shellscape** [ai/nanoid#275]
Ahoy 👋  I was curious if the project would be open to a contribution of some CLI improvements. I know that `nanoid-cli` exists, but it's dang near three years out of date and while I have reached out to the author about updating it, the code behind that package is small enough that I wondered if there's openness now to having that integrated as part of `nanoid` proper.

**Comment by ai** [comment]
Sure. What do you want to change in current CLI?

**Comment by shellscape** [comment]
Specifically, I'd like to add alphabet and length flags. We're using this in a script for using the AWS CDK via bash and need to generate uuids inline. It could be done via a local node script but would be much more convenient to specify on the CLI.

**Comment by ai** [comment]
Yeap, send PR. And add `--help` to explain arguments.

**Comment by TrySound** [comment]
What do you want to use for parsing flags?

**Comment by ai** [comment]
No dependencies can be added (we have 0 dependencies, and adding dependency for rate feature will be bad for marketing).

Parse them manually.

**Comment by shellscape** [comment]
No worries, I can handle that.
