### ISSUE TITLE
Define forbidden characters for first, last position and leading character

### ISSUE THREAD

**Issue by radeno** [ai/nanoid#28]
Many people like me use this library as unique URL identifier and it works really good.

One thing should be better to generate friendly URLs. Restrict first and last characters like underscore and tilde ( _ ~ ) from default character set.
It is better human readable when ID is something like this: 0BM_z7D than this 0BMOz7_ or ~BMOz7D.

Same case why we should restrict special characters is when they leading next to each other.
Currently we can get some of these combinations: 0B__z7D, 0B~_z7D which also doesn't look so good.

**Comment by ai** [comment]
If you will forbid some symbols in start/end it will be bad for distribution.

If in you case you have problem with this symbols it will be better (more secure) to remove them from alphabet and increase ID length (to keep same collision probability).
