### ISSUE TITLE
Webpack compiles the node version into the web project and throws errors

### ISSUE THREAD

**Issue by BassOfBass** [ai/nanoid#280]
```
ERROR in ./node_modules/nanoid/index.js 1:0-27
>Module not found: Error: Can't resolve 'crypto' in '[[ path ]]\node_modules\nanoid/'
BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.
If you want to include a polyfill, you need to:
        - add a fallback 'resolve.fallback: { "crypto": require.resolve("crypto-browserify") }'
        - install 'crypto-browserify'
If you don't want to include a polyfill, you can use an empty module like this:
        resolve.fallback: { "crypto": false }
```
First off props to webpack for misleading error messages, took me a while to really get it. But the problem it seems that webpack thinks it builds for the node environment and picks `index.js` instead of `index.dev.js`/`index.prod.js` respectively. Reproduction repo doesn't have this problem (although it was bootstrapped with webpack command, while the current config was made from the ground), so I'll just link files in question:
- [base config](https://github.com/BassOfBass/BassOfBass.github.io/blob/master/webpack.common.js)
- [dev config](https://github.com/BassOfBass/BassOfBass.github.io/blob/master/webpack.dev.js)
- [prod config](https://github.com/BassOfBass/BassOfBass.github.io/blob/master/webpack.prod.js)
- [the file `nanoid` gets imported to](https://github.com/BassOfBass/BassOfBass.github.io/blob/master/src/lib/_index.js)

I get this error in both modes.
After setting `resolve.fallback: { "crypto": false }` it throws `Buffer is not defined` in the browser console instead.
As per [webpack docs](https://webpack.js.org/concepts/targets/#multiple-targets) `output.target` defaults to `web` so I have no idea why it goes for node package.

**Comment by ai** [comment]
> But the problem it seems that webpack thinks it builds for the node environment and picks index.js instead of index.dev.js/index.prod.js respectively.

Yeap, the source of the problem is that webpack try to bundle a wrong file.

What `nanoid` version do you use? Can you try 3.1.23 and 3.1.22?

**Comment by BassOfBass** [comment]
Turns out the problem was in [this line](https://github.com/BassOfBass/BassOfBass.github.io/blob/7869ec024e6ca6e161b63caf5adb59920e0c0750/webpack.common.js#L45). These folder-like extension resolves didn't bode well with `nanoid` for whatever reason.
