### ISSUE TITLE
Feasibility for usage in AWS Lambda

### ISSUE THREAD

**Issue by stefanesterer** [ai/nanoid#289]
First let me say: Thx for all the work and the great readme!

In one of my projects we are migrating applications from e.g. kubernetes java pods to services comprised of AWS lambdas. Right now we are using a stateful id generator (based on twitter snowflake, https://developer.twitter.com/en/docs/twitter-ids).  

Nanoid (with it's javascript and python implementation) seems like a perfect match for this new use case. My only concern/question is, if by using nanoid in AWS lambda we are running into problems with nanoid not having enough entropy to create secure ids. 

The readme says:
> Nano ID uses the crypto module in Node.js

So for I guess for the node.js AWS lambda environment we should be fine. I'm a little bit unsure about the python implementation (https://github.com/puyuan/py-nanoid). Do you have insights for that library too?

Thx for your help!

**Comment by ai** [comment]
You should ask Python implementation author. I do not know Python to help you.

**Comment by stefanesterer** [comment]
> You should ask Python implementation author. I do not know Python to help you.

Thx for the info about the python implementation. I will ask there. But am I right with my assumption that by using node.js in the AWS lambda environment we shouldn't run into entropy problems by using (the javascript implementation of) nanoid?

**Comment by ai** [comment]
As I understand, Node’s `crypto` wait for entropy collection, so it will always work.
