### ISSUE TITLE
Importing from Unpkg fails with 404 on `crypto` dependency.

### ISSUE THREAD

**Issue by milochristiansen** [ai/nanoid#290]
The very first line in the module returned by unpkg is:
```js
import crypto from "https://unpkg.com/crypto@latest?module";
```
Which is a 404.

What is this "crypto" library, and where is it actually? I'm using import maps in my project so I can forcibly patch the issue if I know where to find the module I need.

For now I'm using the `nanoid/non-secure` package since that one is *actually* zero dependencies, but it obviously isn't ideal.

**Comment by ai** [comment]
You need to load `/nanoid.js` instead of `/index.js`.

Something like `https://unpkg.com/nanoid/nanoid.js`

**Comment by milochristiansen** [comment]
That does indeed work. I'm not sure why Unpkg would give me the wrong file by default. something is probably misconfigured.

**Comment by ai** [comment]
It gives you default file, but this file was created for Node.js and doesn’t work in browser.

You can ask Unpkg to support `package.browser` key.
