### ISSUE TITLE
Hitting process.env.NODE_ENV in Svelte with Rollup

### ISSUE THREAD

**Issue by ianengelbrecht** [ai/nanoid#293]
Hey guys, I'm building a Svelte project with Rollup. If I use `import { nanoid } from "nanoid"` I get a 'process' does not exist error because of the process.env.NODE_ENV  in line 6 of index.browser.js. I see this was discussed in issue #237 and some other related issues, but it does not appear to be resolved. 

If I use `import { nanoid } from "nanoid/nanoid.js"` then it works, but that means I can't import and test my functions independantly in Node. What we need is `import { nanoid } from "nanoid"` that than can be used in browser or node independently of a bundler. I appreciate this is not easy though with the whole commonjs/esm situation.

**Comment by ai** [comment]
You need to use this plugin to add `process.env.NODE_ENV` to Rollup https://www.npmjs.com/package/@rollup/plugin-replace
