### ISSUE TITLE
Package.json inconsistency on npm vs github — missing index.cjs in browser field — leads to browserify inlining crypto module

### ISSUE THREAD

**Issue by arturi** [ai/nanoid#294]
Thanks for the great module!

The [`package.json` in the repo](https://github.com/ai/nanoid/blob/2f55546debe3dae54ba37e3d6b76e87f11b2a668/package.json#L21-L26) differs from [the one released on npm](https://unpkg.com/browse/nanoid@3.1.23/package.json): mainly the problem is that the `browser` field doesn’t include the the `index.cjs`, which is listed in `main` field. Which leads to Browserify picking the node version, and bundling the whole Node’s `crypto` module.

How to fix: release the current package.json on npm.

**Comment by ai** [comment]
`dual-publish` changes `package.json`. It moves `browser`’s subfolder to `async/pakage.json`, etc.

Can you send PR to `dual-publish` to keep origin `package.browser`? https://github.com/ai/dual-publish/

**Comment by arturi** [comment]
I’m a bit confused. Should I add a `cjs` handling, similar to this: https://github.com/ai/dual-publish/blob/8f2097ad63797121677dcb87d0c4ed22aa47472b/process-dir.js#L150-L153?

`'./index.cjs': './index.browser.cjs'`

**Comment by ai** [comment]
Nope, browser should use ESM

**Comment by arturi** [comment]
Yes, right. Still confused though. dual-publish is creating / replacing stuff in the `browser` field of `package.json`, how can I just keep the original?

**Comment by ai** [comment]
You can take original object and replace just part of it

**Comment by ai** [comment]
Fixed in 3.1.24
