### ISSUE TITLE
React Native support

### ISSUE THREAD

**Issue by mateuscalza** [ai/nanoid#30]
I found a problem while running on React Native.
![image uploaded from ios](https://user-images.githubusercontent.com/4462031/31452587-bd921ff0-ae85-11e7-8672-699a1dcadceb.png)
Are there any plans to support React Native?

**Comment by ai** [comment]
Hm. Interesting case. I have few questions for you as for RN developer:

1. What is JS API to get hardware random generator?
2. How I can change some file for RN (as we change `random.js` to `random-browser.js` by `browser` properties in `package.json`)

**Comment by ai** [comment]
Seems like React Native support is not so easy :(. There is no JS API for random bytes.

So, my recommendation:

1. Install [react-native-randombytes](https://www.npmjs.com/package/react-native-randombytes).
2. Use `format(rnRandom, urlAlphabet)` https://github.com/ai/nanoid#custom-random-bytes-generator

**Comment by mateuscalza** [comment]
Exactly, I just checked and there is not even a specific API for this.
But your solution looks like it will solve! Thank you!

**Comment by ai** [comment]
@mateuscalza if this solution will fix the problem, can you add steps to README?

**Comment by mateuscalza** [comment]
Yes, I'll do it as soon as I can test it.

**Comment by mateuscalza** [comment]
It did not work as expected, because of this question: [https://github.com/mvayngrib/react-native-randombytes/issues/10](https://github.com/mvayngrib/react-native-randombytes/issues/10)
I'll keep track of this, and as soon as I get a simple solution I'll update you.

**Comment by gimyboya** [comment]
any update on this issue?

**Comment by ai** [comment]
I will made a solution in the airplane today. Note, that solution will not be secure (ID will be theoretical predictable).

**Comment by ai** [comment]
The non-secure random generator was added to support RN https://github.com/ai/nanoid/commit/aa39d813f16b30ef4e122e3a99e76f3fca417591

We even added a special warning in `index.js` https://github.com/ai/nanoid/commit/dc7a74e8d80aaa73895cf8e7cf7ee45dfd0d91c0

**Comment by ai** [comment]
Released in 1.1
