### ISSUE TITLE
why is { nanoid } not exported as default?

### ISSUE THREAD

**Issue by iambumblehead** [ai/nanoid#317]
in the spirit of nano-sized things, why is nanoid not exported as 'default' to allow smaller import?
```javascript
import nano from 'nanoid'; // doesn't work currently
```

**Comment by TrySound** [comment]
Default export does not work very well
https://github.com/ai/nanoid/issues/306
https://github.com/ai/nanoid/issues/187

**Comment by ai** [comment]
Default export doesn’t work in webpack for dual ESM/CJS packages

**Comment by iambumblehead** [comment]
@ai have you tried exporting nanoid as BOTH default and named export from the same file?

**Comment by TrySound** [comment]
This will lead to even more problems with webpack itself and other tools.

**Comment by TrySound** [comment]
Like this
```
import nanoid from nanoid
console.log(nanoid.default.default())
```

**Comment by TrySound** [comment]
It's also a bad practice to allow inconsistent usages.

**Comment by iambumblehead** [comment]
thanks for the explanation. I'm sorry for everyone that needs to use webpack.

**Comment by TrySound** [comment]
I'd say the problem here is default export which is not obvious how to interop with commonjs. And all tools do it differently. I prefer to avoid it everywhere.

**Comment by iambumblehead** [comment]
@TrySound thanks elaborating on that. I understand and agree, though I will continue using default exports.

**Comment by iambumblehead** [comment]
@TrySound @ai I appreciate your responses and recognize you do not wish to change the way things are setup here BUT for the sake of completeness I would like politely suggest one last approach. I have used this approach and mention this simply to say that I've had a good experience with it. 

**Use an mjs/esm file as the 'main' file and use sed rather than babel** to generate cjs files. Using sed, one can control the export definition and avoid 'default.default' situations. Here's what it would look like:

_nanoid.mjs_
```javascript
export default nanoid;
```

then convert the file with sed
_package.json_
```json
{
  "scripts": {
    "generate": "cp nanoid.mjs nanoid.js && sed -i 's/export default/module.exports =/' nanoid.js"
  }
}
```

I've used the approach here https://github.com/iambumblehead/form-urlencoded/blob/master/package.json#L59 When I stopped using babel, problems went away and people stopped opening import/export-related issues

nanoid would need an extra sed command to convert "let { urlAlphabet } = require('./url-alphabet')" to "import { urlAlphabet } from './url-alphabet.js'"

other definitions could be defined on nanoid this way,
```javascript
Object.assign( nanoid, { customAlphabet, customRandom, urlAlphabet, random });
```

This last suggestion may not convince you but I wanted to let you know about it anyway. Thanks for reading me :)

**Comment by ai** [comment]
The problem is in different behavior of default export in Node.js ESM and webpack ESM. This solution will not work.

**Comment by iambumblehead** [comment]
If there were a default export that could be demonstrated to work with webpack ESM, would it change your mind?

**Comment by ai** [comment]
> If there were a default export that could be demonstrated to work with webpack ESM, would it change your mind?

If you show me popular library with default dual ESM/CJS export.

Nano ID is very popular library. You can show me a one example, when everything is working, but real users will find a case when everything is broken. It is just a big risk for me. So I need not an example, but a reason to trust that this method will work in many different scenarios.

**Comment by iambumblehead** [comment]
@ai understood and agreed! I doubt I could find such a case and respect keeping things as they are to avoid problems for users.

form-urlencoded gets npm downloads between 150,000 and 200,000 a week but this pales to nanoid's current weekly downloads of 15,165,562. Thanks for reading and responding to me here.

**Comment by ai** [comment]
Can you create another Node.js library which will use `form-urlencoded` and then use this lib in app in Node.js, webpack, Parcel, TypeScript?

(Also note that I will add default export only in 4.0 release, which will be only a year after).

**Comment by iambumblehead** [comment]
@ai I could do that. I'm not experienced with all of those tools but would do my best. The package could be named something like "default-import-test-scenarious" so that it might ultimately be used to verify packages other than form-urlencoded.
