### ISSUE TITLE
Why the if statement check on the alphabet array in Format.js?

### ISSUE THREAD

**Issue by davidklebanoff** [ai/nanoid#32]
Seen here:
https://github.com/ai/nanoid/blob/fbe56a27637068a64648290f48fc5aa1093ed525/format.js#L35

What's the reason for the if statement? Is this a holdover from before the mask was calculated?

Maybe I'm missing something. But, if it's removed. It clean up the code a lot as the while loop would disappear as well.

**Comment by ai** [comment]
Because `byte` could contain number bigger than alphabet length.

For example, if alphabet size i 5 symbols (`abcde`), nanoid’s random generator will put to `byte` numbers between `0…7`. `0, 1, 2, 3, 4` is correct positions in the alphabet, but `5, 6` will be out of alphabet size.

**Comment by davidklebanoff** [comment]
Ah, right. For some of the non-default cases.

On an unrelated note, `var byte = bytes[i] & mask` caused a brief moment of confusion when I was looking at the code. At quick glance, based on the variable names alone, one might expect a variable named `byte` would be `var byte = bytes[i]` rather than `var byte = bytes[i] & mask`. Not a pressing matter, but I believe there's room for improvement in the variable name to eliminate any confusion. *shrug*

**Comment by ai** [comment]
I am open for name suggestion :D.

`& mask` reduce cases when we ignore byte when it out of alphabet size (so for 5 symbols alphabet `byte = bytes[i]` will generate numbers between `0…255`, but `byte = bytes[i] & mask` will generate `0..7`)

**Comment by davidklebanoff** [comment]
Right.

Something like `alphabetIndex` might work? It describes its purpose rather than its origin.

**Comment by ai** [comment]
Or maybe `position` or `char`?
