### ISSUE TITLE
Why is non-secure slower than secure?

### ISSUE THREAD

**Issue by MikelArnaiz** [ai/nanoid#321]
```
### Non-Secure

By default, Nano ID uses hardware random bytes generation for security
and low collision probability. If you are not so concerned with security
and more concerned with performance, you can use the faster non-secure generator.
```

Non-Secure is supposed to be faster than secure. But both Readme's benchmark and one run by myself says the opposite.

```
nanoid                     3,988,856 ops/sec
nanoid/non-secure          2,252,395 ops/sec
```

Why is this?
Does the smartness behind `nanoid` make it fast even in secure mode? if so, what's the point of `non-secure`?
Are these results platform dependant? Readme might need to get updated.

**Comment by ai** [comment]
It was a few releases before. But we add a few very powerful performance improvements to secure version and seems like made it faster than non-secure.

**Comment by ai** [comment]
I updated docs https://github.com/ai/nanoid/commit/efd8302fc811fb9cf23848115400eca84323fb51
