### ISSUE TITLE
[Question] Gradually increment size ?

### ISSUE THREAD

**Issue by KaKi87** [ai/nanoid#322]
Hello,

I would like to create an URL shortener using Nano IDs with the alphanumeric alphabet, starting at a size of 3 characters, and automatically increment as collision probability increases.

Is there a formula or a lib that can help me compute this ?

Thanks

**Comment by ai** [comment]
Sorry, it is completely different task. I can’t help with the math behind it.

**Comment by KaKi87** [comment]
Hello @kelark, since you created the collision calculator, could you help me with that ? Thanks

**Comment by zelark** [comment]
@KaKi87 I suggest to read these links first
https://en.wikipedia.org/wiki/Universally_unique_identifier#Collisions
https://en.wikipedia.org/wiki/Birthday_problem

You can find implementation of the formulas here https://github.com/zelark/nano-id-cc/blob/master/src/nano_id_cc/calc.cljs

Unfortunately, I can't help you with the task itself.

**Comment by KaKi87** [comment]
This implementation is based on ID generation rate, but what about the existing ID count ?
Actually, my request is a bit related to zelark/nano-id-cc#32.
Thanks

**Comment by zelark** [comment]
@KaKi87 thanks for pointing to the issue, I totally forgot about it.
