### ISSUE TITLE
How does nanoid calculate the collision probability

### ISSUE THREAD

**Issue by amitiwary999** [ai/nanoid#324]
WE are using the nanoid with custom alphabet(only number and small alphabet) and size 15. When I checked the collision probability on the website it shows if we generate 1000 id per second then the collision probability is after 49 years. 1000 id per second is only for us or anyone in the world using nanoid is generating id that also counts in 1000 id per second calculation.

**Comment by ai** [comment]
The calculator repository with code https://github.com/zelark/nano-id-cc/

You should ask question there since I didn’t maintain that calculator.

**Comment by ai** [comment]
> 1000 id per second is only for us

Short answer: yes.

It is only for your case.

**Comment by amitiwary999** [comment]
thanks for clarification
