### ISSUE TITLE
Why not 21 symbols instead of 22?

### ISSUE THREAD

**Issue by davidklebanoff** [ai/nanoid#33]
Reading through the README, it sounds you arrived at the number of symbols so that Nano Id has a greater than or equal number of unique combinations when compared to UUID v4. Right?

According to [wiki](https://en.wikipedia.org/wiki/Universally_unique_identifier), UUID v4 has 122 bits that contribute to randomness.

Default Nano ID has a (26+26+10+2 = **64**) symbol alphabet (6 bits). So with 6 bits per symbol, and 22 symbols, we arrive at (6*22 = **132**) total bits.

So we could totally drop the number of symbols down to 21 (126 bits) and still have more unique combinations than UUID v4.

Saves everyone 1 whole symbol! Unless of course I'm missing something, which is very much possible.

**Comment by ai** [comment]
Hm. Really good idea. My origin ID length calculation was not really accurate (I thought only about be bigger).

Send PR (code and docs).

**Comment by ai** [comment]
Released in 1.0.
