### ISSUE TITLE
V3 brokes IE

### ISSUE THREAD

**Issue by AvraamMavridis** [ai/nanoid#336]
The way the V3 is exported prevents proper traspilation and because of the arrow functions the package is not working on IE11. Any plans to provide a es5 compatible build?

v3 output of webpack with es5 target (arrow functions still there):

![Screenshot 2022-01-20 at 09 35 17](https://user-images.githubusercontent.com/283690/150309481-43a7ef73-51fa-480c-8ed5-8ed5655d9900.png)

v2 output of webpack with es5 target (no arrow functions):

![Screenshot 2022-01-20 at 09 50 45](https://user-images.githubusercontent.com/283690/150309496-82a93027-ccec-44ef-b9f8-db106eb2258d.png)

**Comment by ai** [comment]
We have a notice in docs with a solution
https://github.com/ai/nanoid#ie

We made this choice to make JS move forward without blocking from very old IE 11. If you need to support IE 11 you can use many tools to compile JS.
