### ISSUE TITLE
Version 3.1.30 changes random values with predefined seed

### ISSUE THREAD

**Issue by alexeychikk** [ai/nanoid#345]
The following code consistently output value `74vpt` prior to the version `3.1.30` after which it started to output a new value `CxZwF`:

```js
import { customRandom, urlAlphabet } from "nanoid";
import seedRandom from "seedrandom";

const generateRandomNumber = seedRandom("my-seed");

const generateId = customRandom(urlAlphabet.replace(/_|-/g, ""), 5, (size) => {
	return new Uint8Array(size).map(() => 256 * generateRandomNumber());
});

console.log(generateId());
```

Seems like version 3.1.30 of `nanoid` changes how random id-s are generated which seems like a breaking change to me.

**Comment by ai** [comment]
Unfortunately, it is expected. We do not guarantee the same call of random generator.

Since we try to be as small as possible, we sometimes change generator calls sequence.

If you help me with a good test for this, I can try to make only major changes. Or we can change docs to warn about it.

**Comment by ai** [comment]
I updated docs f1ab53a
