### ISSUE TITLE
Nano ID vs UUID Base64

### ISSUE THREAD

**Issue by tkrotoff** [ai/nanoid#350]
The README states:

> There are three main differences between Nano ID and UUID v4:
> 1. Nano ID uses a bigger alphabet, so a similar number of random bits are packed in just 21 symbols instead of 36.

This is unfair: Nano ID should be compared to UUID Base64 or [Base64url](https://en.wikipedia.org/wiki/Base64#The_URL_applications) encoded.

- `3a34ea98-651e-4253-92af-653373a20c51` original UUID => 36 symbols
- `OjTqmGUeQlOSr2Uzc6IMUQ` same UUID but Base64url encoded => 22 symbols
- `V1StGXR8_Z5jdHi6B-myT` Nano ID => 21 symbols
- `-IvvARlqMW8` YouTube ids => 11 symbols

**Comment by ai** [comment]
Many people use UUID directly. This not is for these people.
