### ISSUE TITLE
Postgres extension of nanoid written in rust

### ISSUE THREAD

**Issue by spa5k** [ai/nanoid#358]
Hey, I created a postgres extension that was written in rust, and can be used in postgres to generate nanoid values for various stuff.

check it here - [spa5k/uids-postgres](https://github.com/spa5k/uids-postgres)

mainly created it for experiment and lack of a good postgres extension written in ksuid, ulid and nanoid.

One extension for all 3 of em.

**Comment by ai** [comment]
Looks good!

1. Do you use hardware random generator?
2. Can you send PR to docs with a link to your project?

**Comment by spa5k** [comment]
I'm using the https://github.com/nikolay-govorov/nanoid, the library that is mentioned in the readme, and from the looks of it, it is using hardware generation.

**Comment by spa5k** [comment]
Coming to PR, at which category of README, should i add it?

**Comment by ai** [comment]
`Other Programming Languages`, maybe.

Don’t forget also to add to `README.cn.md`, etc (don’t need to translate list item).
