### ISSUE TITLE
Uncaught ReferenceError: Buffer is not defined

### ISSUE THREAD

**Issue by MaleWeb** [ai/nanoid#366]
![image](https://user-images.githubusercontent.com/20508968/172986990-d911e497-adb4-4f97-abaa-5a48d7d4695b.png)

**Comment by ai** [comment]
What tool do you use to bundle JS to JS bundle? Webpack, esbuild? What versions?

**Comment by hold-baby** [comment]
```js
import { nanoid } from "nanoid/index.browser";
```

**Comment by vyadl** [comment]
Got the same error. The problem was in the bundler. In my case It was rollup and for making bundle compatible with browser there is should be passed some extra option in resolve() step.

rollup.config.js
```js
...
resolve({
  browser: true,
}),
...
```
