### ISSUE TITLE
[QUESTION] How to check nano id is valid or not? 

### ISSUE THREAD

**Issue by highRisk1** [ai/nanoid#368]

**Comment by MCArth** [comment]
i mindlessly copy pasted this so for anyone else who might do the same, \w doesn't taken into account the - and _ in nanoids

`/[A-Za-z0-9_-]{21}/.test(id)` works

`/[A-Za-z0-9_-]{21}/.test("V1StGXR8_Z5jdHi6B-myT")` => true (correct)
`/\w{21}/.test("V1StGXR8_Z5jdHi6B-myT")` => false (incorrect)

**Comment by MCArth** [comment]
The above will match strings of length > 21, so should also check the string's length directly
