### ISSUE TITLE
require error

### ISSUE THREAD

**Issue by andersonSanchezS** [ai/nanoid#370]
when i use the lastest version(4.0.0) and  i try to use the library the package throws this error 
[ERROR] 22:15:17 Error: require() of ES Module /home/gadget/Documentos/Code/personal/NodeJs/BlogAPI/node_modules/nanoid/index.js from /home/gadget/Documentos/Code/personal/NodeJs/BlogAPI/src/dataSources/models/categories/index.ts not supported.
Instead change the require of index.js in /home/gadget/Documentos/Code/personal/NodeJs/BlogAPI/src/dataSources/models/categories/index.ts to a dynamic import() which is available in all CommonJS modules.

i solved downgrading the package version to 3.3.4

**Comment by ai** [comment]
Yes, it happens because in 4.0 we moved to ESM.

**Comment by ai** [comment]
We still support 3.x branch. You do not need to update to 4.0 if you have CJS app.
