### ISSUE TITLE
Maintenance of last Non-ESM release

### ISSUE THREAD

**Issue by konradjurk** [ai/nanoid#372]
Hi 👋

Due to our server (Nest.js, [source](https://discord.com/channels/520622812742811698/975798881667391518/975799372631662632)) as well as testing framework (Jest, [source](https://jestjs.io/docs/ecmascript-modules)) currently being incompatible or not sufficiently stable with ESM, we can't upgrade to your latest major version.

We are wondering if you are planning to continue to supply security updates to the last non-ESM release.

Thank you!

**Comment by ai** [comment]
Of course! Here is a quote from ChangeLog:

> We will support 3.x branch with CommonJS for users who can’t migrate to ESM.

We plan support at least for a few years.

**Comment by konradjurk** [comment]
Thanks @ai and sorry that I overread it!
