### ISSUE TITLE
Recommended dictionary for a 256 character set?

### ISSUE THREAD

**Issue by slimhk45** [ai/nanoid#373]
I would like to have a dictionary of well chosen 256 characters to generate a UUID V4-compliant as short as possible (maybe 6 or 8 I don't know).
Can you add a recommended dictionary for this? Maybe using the greek alphabet also, but this will not be enough. What about emoji?

**Comment by ai** [comment]
There is no way to make it URL safe. I can’t create a dictionary without knowing the use cases and limits.

> What about emoji?

Do you need small ID in bytes or in symbols rendering on the screen?

Emoji symbol is very long in bytes.

**Comment by slimhk45** [comment]
I want small ID short in symbols rendering on the screen. I need that for an important utility I'm coding to manage my files (I want to create a portable UUID as filename convention in case I move my files to another cloud storage to recover the link).

**Comment by ai** [comment]
Do you need to be able to input this symbols by keyboard or just copy-pasting?

**Comment by slimhk45** [comment]
Copy pasting, they will be automatically generated (by right clicking in the file explorer, or sharing the file on mobile device). I will create a custom URI scheme (for instance something like fs:uuid) that will be parsed by my utility to automatically open or go to the corresponding file in the file explorer/cloud storage app. It's not perfectly defined right now, I have the global idea of what I need to do, but the first problem is having the shortest ID possible not to clutter my filename views.

**Comment by slimhk45** [comment]
The conventions might be
filename.{UUID}.extension
foldername {UUID}

**Comment by ai** [comment]
In this case, the best alphabet for your case will be to choose 256 emoji according to your preferences.

I think mixing emojis with non-emojis will looks worse.

**Comment by slimhk45** [comment]
Oh maybe if I use varying-lenght ID that will augment the range of possible ID generated from the 64 character set while keeping it below 8 characters?

1st I generate a number with nanoid between 1 and 8 to get the ID size.
Then I generate the ID.

I don't know if this can be UUID V4 compliant in terms of collision.

**Comment by ai** [comment]
varying-lenght IDb is more hard to implement. Stable length is a safer option.

**Comment by slimhk45** [comment]
So I checked and I found two solutions :

I can use the Braille character https://en.wikipedia.org/wiki/Braille_Patterns which is an interesting character set that is exactly of 256:. it's the most interesting character set I found because we never need to "see Braille", so the characters appear nowhere else, and there is exactly 256 configurations for a Braille. To keep that compact I use 6 characters.

Or I use a varying-lenght ID from 1 to 8 characters with the standard base64 character set, but I use the padding character (usually the sign "=") to keep the lenght constant for keeping the parsing of filename easy..

I computed both case and they return similar collision probability. The first scenario is more compact. but use an exotic set.

**Comment by ai** [comment]
> I can use the Braille character

I like this idea 😁

> I computed both case and they return similar collision probability

Collision probability calculation could be very tricky if you have multiple machines.

For instance, `shortid` used varying-lenght ID, but it required unique machine ID in options.

**Comment by slimhk45** [comment]
Yeah but anyway, the varying lenght is just to increase slightly the set because I don't like to waste data 🤣. But it's almost the same probability because the power of 8 is so big compared to the power of 7, 6 etc... (64**8 >> 64**7 + 64**6 + 64**5 + 64**4 + 64**3 + 64**2 + 64 + 1). 
Actually **256**6 = 64**8**
So it's more a question of which character set is the most appealing. I'll think about it.

**Comment by slimhk45** [comment]
You should add the Braille set as a recommend nanoid dictionary for 256 😁

**Comment by ai** [comment]
Should we send PR to https://github.com/CyberAP/nanoid-dictionary ?

**Comment by slimhk45** [comment]
Yeah I think that's a good idea 👍

**Comment by slimhk45** [comment]
CORRECTION: there is already a standard set for 32 charachters (latin alphabet + number 2-7 to avoid confusions between letters and numbers)
