### ISSUE TITLE
Documentation should reflect that customAlphabet is a generator

### ISSUE THREAD

**Issue by theredwillow** [ai/nanoid#377]
The [readme states](https://github.com/ai/nanoid#custom-alphabet-or-size) that "customAlphabet allows you to create nanoid with your own alphabet and ID size."

This language is not inherently obvious that it is a generator (i.e. a function that creates a function).

The example does help, but this is such a commonly used function that I believe many people will accidentally look over the call (i.e. ()) used.
```
import { customAlphabet } from 'nanoid'
const nanoid = customAlphabet('1234567890abcdef', 10)
model.id = nanoid() //=> "4f90d13a42"
```

**Comment by ai** [comment]
What changes do you suggest?

**Comment by theredwillow** [comment]
"customAlphabet **returns a function** that allows you to create nanoid with your own alphabet and ID size"

**Comment by ai** [comment]
Sure! Good suggestion. Please send PR to save your name in the project’s history.

**Comment by theredwillow** [comment]
https://github.com/ai/nanoid/pull/378

**Comment by ai** [comment]
Thanks
