### ISSUE TITLE
Nano ID Giving Same Random Number Each Time...

### ISSUE THREAD

**Issue by Be1newinner** [ai/nanoid#387]
var nanoid = customAlphabet('1234567890', 6);

var random = nanoid;

it returning same otp for a limited time... 

![image](https://user-images.githubusercontent.com/81816619/190329089-84dd0afe-b1ae-47f7-8d69-cc7c82f40e66.png)

Edited : removed random number it still gives the same random number each time...

**Comment by ai** [comment]
What `random` do you use in this example?
