### ISSUE TITLE
[Technical question] 25 or 26 characters for base32 encoding?

### ISSUE THREAD

**Issue by slimhk45** [ai/nanoid#391]
Hi, I need base32 uuid to encode hex uuid in filenames with fewer characters.
But I'm confused: 128/5=25.6. Should I use 25 or 26 characters? Similarly, nanoid choose 21 characters over 22 (128/6=21.3). Why this choice?

Also a last question, what is the advantage of the base32hex (0-9, A-V) over the base32 (A-Z, 2-7) in this case (filename uuid)?

Thanks.

**Comment by ai** [comment]
26.

You need to choose bigger number to have not-less bit amount.

> Also a last question, what is the advantage of the base32hex (0-9, A-V) over the base32 (A-Z, 2-7) in this case (filename uuid)?

Sorry, don’t know.

**Comment by slimhk45** [comment]
But why nanoid choose less then? That's why I don't understand, you have rounder to 21, you should to 22 characters then?

**Comment by ai** [comment]
Sorry, it is mobilization happening in my country. I don’t have resources to remember the math.
