### ISSUE TITLE
GUID comparison

### ISSUE THREAD

**Issue by orefalo** [ai/nanoid#403]
Greetings,

I am compiling a GUID summary sheet which tries to aggregate different dimensions with the intent to help engineers pick the right generator.

Would you be kind enough to help me validate the Nanoid column and point to any issues?

Thank you

![image](https://user-images.githubusercontent.com/52085/210317631-e652ce63-408a-4f95-9663-dee07f1cd60e.png)

**Comment by ai** [comment]
Looks good!

Can you ping me when it will be ready, want to share it to my Twitter.

**Comment by orefalo** [comment]
Will surely do,
if you could help me with the items in '??'

**Comment by ai** [comment]
Did you get an updated version? Do you have a Twitter account to mention you?
