### ISSUE TITLE
Is there a way to validate if a string is nanoid?

### ISSUE THREAD

**Issue by andreluizsgf** [ai/nanoid#405]
Hi, i want to use nanoid to generate some random ids but would like to check if a given string is nanoid and then query for it in a database. is this validation possible?

**Comment by ai** [comment]
I think `/[\w_-]{21}/.test(id)` should work

**Comment by thevinitgupta** [comment]
I was also looking for a validator. Is there a method added for this or does the above Regex work properly? @ai

**Comment by ai** [comment]
Yes, it should works.
