### ISSUE TITLE
import { customAlphabet } from 'nanoid' fails in TS -  nanoid@4.0

### ISSUE THREAD

**Issue by wmelton** [ai/nanoid#410]
TypeScript native project, node 18, nanoid@v4

Error message, "Must use import to load ES Module" - Is this error message just a bad message? Meaning, is the issue actually something else?

```ts
import { customAlphabet } from 'nanoid'
```

How else would one include nanoid@4.0 in a TS project except via import at this point?

TSConfig: 

```json
{
    "compilerOptions": {
         "target": "esnext",
        "module": "esnext",
        "lib": ["esnext", "es6", "dom"],
        "moduleResolution": "node",
    }
}
```

**Comment by ai** [comment]
Do you have `"type": "module"` in project’s `package.json`?

Do you have this error on type check or on program execution?

**Comment by wmelton** [comment]
Hey @ai - thanks for the fast response.

package.json:
![image](https://user-images.githubusercontent.com/1544125/219393422-25d1d856-43f3-449c-af77-44d81f62eedc.png)

Program execution, though looking at it now, I need to clarify that it appears this only happens when running Jest tests. When running the main express app, the library performs as expected without error.

Okay, sounds like maybe this is related to Jest's relatively poor support for ESM still. Bummer though - nanoid@3^ works both runtime and within jest executions. 

Guess we'll stick with v3 for now unless there's some fix to make Jest happy too.

**Comment by ai** [comment]
>  I need to clarify that it appears this only happens when running Jest tests

Jest hack `import` and `require()`. I can only send you to Jest team since I can’t help with type of hacks like their.
