### ISSUE TITLE
`expo-random` has been deprecated

### ISSUE THREAD

**Issue by silvestreh** [ai/nanoid#414]
Hi there! I just wanted to give you a quick heads up about [`expo-random`](https://docs.expo.dev/versions/latest/sdk/random/) being deprecated. It'll be removed in the next Expo SDK release.

I *think* you'll want to update [index.native](https://github.com/ai/nanoid/blob/main/async/index.native.js) so that the `import` reads:

```
import * as Crypto from 'expo-crypto'
```

And a couple lines below that

```
export let random = Crypto.getRandomBytesAsync
```

**Comment by ai** [comment]
Can you send a PR? Since I am not a RN developer.

**Comment by silvestreh** [comment]
@ai thanks for the quick reply. Here's the PR https://github.com/ai/nanoid/pull/415 :)
