### ISSUE TITLE
Cannot be installed with node 12

### ISSUE THREAD

**Issue by kajweb** [ai/nanoid#417]
nanoid@4.0.1: The engine "node" is incompatible with this module. Expected version "^14 || ^16 || >=18". Got "12.22.12"

**Comment by ai** [comment]
Yes. Node.js 12 doesn't have security fixes anymore and should not be used.

https://nodejs.dev/en/about/releases/

**Comment by masudhossain** [comment]
Was this a recent change? I've been using node12 for a while now.

> Yes. Node.js 12 doesn't have security fixes anymore and should not be used.
> 
> https://nodejs.dev/en/about/releases/

**Comment by ai** [comment]
@masudhossain about a year ago https://vercel.com/changelog/node-js-12-is-being-deprecated

You should change your policies and practices. Using Node.js 12 in production is dangerous. You should use Node.js 16 or 18.
