### ISSUE TITLE
Semantic versioning

### ISSUE THREAD

**Issue by hampuskraft** [ai/nanoid#419]
Hi there! It seems like the versions were pushed to NPM in the wrong order, meaning that the latest version is not 4.0.2 but 3.3.6, which seems counterintuitive for tools that automatically bump the dependency to the latest version.

<img width="752" alt="image" src="https://user-images.githubusercontent.com/24176136/227898157-6bd7f373-4ea8-450f-a5f5-f7210693bfad.png">

**Comment by hampuskraft** [comment]
Changing the dist-tag of 4.0.2 to "latest" should be possible if you agree that this would be more intuitive: https://docs.npmjs.com/cli/v9/commands/npm-dist-tag.

**Comment by ai** [comment]
I called `npm dist-tag add nanoid@4.0.2 latest` and hope now it was fixed
