### ISSUE TITLE
All monotonically increasing (auto-increment, k-sortable), and timestamp-based ids share the security issues

### ISSUE THREAD

**Issue by DaRabus** [ai/nanoid#420]
Hey Guys,

Just checking here if nanoid() is safe to use, or is it also affected by these security issues?

https://github.com/paralleldrive/cuid

- [Unauthorized password reset via guessable ID](https://infosecwriteups.com/bugbounty-how-i-was-able-to-compromise-any-user-account-via-reset-password-functionality-a11bb5f863b3)
-  [Unauthorized access to private GitLab issues via guessable ids](https://infosecwriteups.com/how-this-easy-vulnerability-resulted-in-a-20-000-bug-bounty-from-gitlab-d9dc9312c10a)
- [Unauthorized password reset via guid](https://www.intruder.io/research/in-guid-we-trust)

**Comment by ai** [comment]
This is why Nano ID is using hardware random generator to have unguessable IDs. Just don't reduce ID length and keep some timeout between tries.
