### ISSUE TITLE
ulid format preset

### ISSUE THREAD

**Issue by martinheidegger** [ai/nanoid#449]
I am happily using nanoid for my project but (for compatibility) I also need to use ulidx, to reduce the dependencies, I was wondering if nanoid could provide a ulid preset and/or a ulid function that is compatible with ulid?

**Comment by ai** [comment]
No, we are not compatible. The idea of the tools is totally different. ulid is sortable ID while Nano ID is fully random.

Both ways have own benefits. You should choose told depending on task.

It is impossible to reconfigure one you another.
