### ISSUE TITLE
Don't use unsafe ~ character.

### ISSUE THREAD

**Issue by zharikovpro** [ai/nanoid#45]
TLDR: follow the RFC for URLs. [Complete reasoning](https://perishablepress.com/stop-using-unsafe-characters-in-urls/).

**Comment by zharikovpro** [comment]
~ can be safely replaced with _

**Comment by ai** [comment]
@zharikovpro we already have `_` in the alphabet.

This article has a problem, it tells that `-` is safe, but it is not https://github.com/dylang/shortid/issues/96
This is a reason why `~` was added to Nano ID, because it is safe in practice and `-` is safe in theory.

Do you know any practical problems with `~`?

**Comment by zharikovpro** [comment]
@ai I personally have no real troubles with `-` or `~`. It's all about quote from [RFC](http://www.ietf.org/rfc/rfc1738.txt):

> Other characters are unsafe because
   gateways and other transport agents are known to sometimes modify
   such characters. These characters are "{", "}", "|", "\", "^", "~",
   "[", "]", and "`".

It *may* be that `~` also has some weird issues, like one that you referenced for the `-`. I posted this issue just in case.

Also, I was choosing a short id lib and came to this warning, so this issue may affect library adoption.

**Comment by ai** [comment]
OK, I will think about it later. Current symbols are safe and work. But I understand that following RFC is good idea.

If you don't like `~` you can replace alphabet. I recommend to not use `-` as well.

**Comment by shesek** [comment]
How about replacing `~` in the alphabet with a `.`?

**Comment by shesek** [comment]
Though, it appears like RFC 3986 says that `~` is URL safe?

```
2.3.  Unreserved Characters

   Characters that are allowed in a URI but do not have a reserved
   purpose are called unreserved.  These include uppercase and lowercase
   letters, decimal digits, hyphen, period, underscore, and tilde.

      unreserved  = ALPHA / DIGIT / "-" / "." / "_" / "~"
```

https://www.ietf.org/rfc/rfc3986.txt

**Comment by ai** [comment]
I afraid `.` in the end of the string will be removed from link on Android and etc

**Comment by ai** [comment]
Also `~` was very popular in 90-2000s as part of user’s directory on the domain: `domain.com/~user`. I think `~` is safe.
