### ISSUE TITLE
strange error

### ISSUE THREAD

**Issue by andrewvlgafc** [ai/nanoid#469]
Hello.

install nanoid v4.0.2 because nodejs is 14.17.6

import as

import { nanoid } from 'nanoid'

on start see error

Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: \node_modules\nanoid\index.js
require() of ES modules is not supported.
require() of \node_modules\nanoid\index.js from \dist\app\PhotoService\upload\init.js is an ES module file as it is a .js 
file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES
 modules.
Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from 
\node_modules\nanoid\package.json.

is possible to start nanoid on nodejs 14.17.6?

**Comment by ai** [comment]
Use `nanoid@3` for legacy project.

The newest Nano ID is for ESM projects.

I am closing this issue as duplicate.

**Comment by andrewvlgafc** [comment]
thanks for fast answer
