### ISSUE TITLE
Is it possible to create a single js file to import in a company inner project?

### ISSUE THREAD

**Issue by cydside** [ai/nanoid#482]
Hi,
I'm a newbie and writing vanilla javascript so could you please let me know, if I missed something in this project home page, how to do a single js file to use it just including `<script src="/public/js/nanoid.js"></script>` in the html source code?
Thanks in advance,
Danilo

**Comment by ai** [comment]
Here is the solution:

```js
import { nanoid } from 'https://cdn.jsdelivr.net/npm/nanoid/nanoid.js'
```

Put it to your vanilla JS and browser will download the file. 

Not only that it is slow for end-users. Use it only for hacks and development.

**Comment by cydside** [comment]
Thanks! Just last think...How can I add a custom alphabet?

**Comment by ai** [comment]
There is no export for that. You need to build your own file using `esbuild`.

**Comment by ai** [comment]
Use:

```js
import { customAlphabet } from 'https://cdn.jsdelivr.net/npm/nanoid/index.browser.js'
```

**Comment by cydside** [comment]
Got it, many many thanks!
