### ISSUE TITLE
How to generate “language-safe”

### ISSUE THREAD

**Issue by Mayccoll** [ai/nanoid#53]
Hi, There is a way to generate IDs words avoiding bad words ?
Here a nice ref:
https://github.com/LDNOOBW/List-of-Dirty-Naughty-Obscene-and-Otherwise-Bad-Words
Thanks

**Comment by ai** [comment]
It will affect to distribution and reduce security, so we can't put it to the core.

But if you don't use ID as a private key you can do something like:

```
let id
do {
  id = nanoid()
} while (!hasBadWord(id))
```

Do you want to make a JS library on top of Nano ID? Something like `nanoid-good`.

**Comment by y-gagar1n** [comment]
Hi, I've made a library for that: 
https://github.com/ai/y-gagar1n/nanoid-good

**Comment by ai** [comment]
@y-gagar1n it was really quick!

Feel free to release it on npm.

**Comment by ai** [comment]
@y-gagar1n please send PR to `nanoid` docs with link to your project in Tools section
