### ISSUE TITLE
it cannot support ie10

### ISSUE THREAD

**Issue by pekonchan** [ai/nanoid#56]
i find that this cannot support ie10 ,  so sad

**Comment by ai** [comment]
What error did you have? Maybe we can fix IE 10 support.

**Comment by pekonchan** [comment]
it show : 
cannot get the undefined or null property "getRandomValues"  in file: random-browser.js

**Comment by NekR** [comment]
I'm actually getting the same error in Edge 17 in Service Worker. Running code manually in console works though. Looking into it now.

**Comment by ai** [comment]
I will try to look on next week.

Maybe it is a problem with `self`

**Comment by ai** [comment]
@NekR if you want you can try to find a solution. I will not be able to look on it in this weekend (having a flight).

**Comment by NekR** [comment]
@ai so the issues seems to be very simple -- Edge still doesn't support `crypto` in workers, including ServiceWorker https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/7607496/

And IE10 doesn't have `crypto` implemented at all (first implementation as `msCrypto` is in IE11).

Hence the errors.

**Comment by ai** [comment]
Hm. You can you `nanoid/format` and combine it with some non-secure random generator.

I will update a docs for this case.

**Comment by zentuit** [comment]
Hi @ai ... just double checking that this means Nano ID doesn't work on Edge and if we need to support it we need to replace the default random generator?

**Comment by ai** [comment]
@zentuit Nano ID works in Edge. It doesn’t work in Web Workers in Edge.

In Web Workers you need to use `nanoid/generate` with some pseudo-random generator (here is [docs](https://github.com/ai/nanoid#custom-random-bytes-generator), the generator can be found on the Internet). Note, that pseudo-random generator is not secure (do not generate secure tokens by it).

After a conference, I am planning to improve docs for Edge’s Web Workers.

**Comment by zentuit** [comment]
@ai -- Ah gotcha, its just Web Workers in Edge.  I misread.  Thanks for clarifying!

**Comment by ai** [comment]
The non-secure random generator was added to support IE 10 and Edge’s Web Workers https://github.com/ai/nanoid/commit/aa39d813f16b30ef4e122e3a99e76f3fca417591

We even added a special warning in `index.js` https://github.com/ai/nanoid/commit/dc7a74e8d80aaa73895cf8e7cf7ee45dfd0d91c0

**Comment by ai** [comment]
Released in 1.1
