### ISSUE TITLE
nanoid in Clojure and ClojureScript

### ISSUE THREAD

**Issue by zelark** [ai/nanoid#57]
Hi, I ported nanoid in Clojure and CojureScript.
You can find it [here](https://github.com/zelark/nano-id).

**Comment by ai** [comment]
Awesome! Can I ask you to send PR and add them to [this list](https://github.com/ai/nanoid#other-programming-languages) (the list is alphabetical)?

We will save your name in project history :).

**Comment by zelark** [comment]
My pleasure!
