### ISSUE TITLE
Weird url in index.browser.js?

### ISSUE THREAD

**Issue by bmathews** [ai/nanoid#66]
Is this correct?

```
var url = '_~getRandomVcryp0123456789bfhijklqsuvwxzABCDEFGHIJKLMNOPQSTUWXYZ'
```

https://github.com/ai/nanoid/blob/master/index.browser.js#L3

**Comment by ai** [comment]
Yeap. We change an order to make Nano ID smaller after gzip https://github.com/ai/nanoid/pull/64
