### ISSUE TITLE
Node 9 in Travis Ci config

### ISSUE THREAD

**Issue by DanielRuf** [ai/nanoid#67]
Not sure if we should just test 6, 8 and 10 (like in most projects) or is it intended to also test Node.js 9?

**Comment by ai** [comment]
O, Node.js 9 support was dropped at July 30. Amazing :)

> like in most projects

Most of the project, supports only LTS releases and I didn’t support them in it :-P

Do you want to send PR with dropping Node.js 9 from Travis CI to save your name in project history?

**Comment by DanielRuf** [comment]
> Do you want to send PR with dropping Node.js 9 from Travis CI

Will do so, wait a moment.
