### ISSUE TITLE
Add Chinese docs

### ISSUE THREAD

**Issue by ai** [ai/nanoid#71]
@wenliangdai @gucong3000 hi, thanks for the help in translating PostCSS docs.

This project got 1M/month downloads. Maybe you want to translate it too? The docs are not so big. And it will be a good reason to mention your in tweets. =^_^=

**Comment by wenliangdai** [comment]
@ai Hi, I can do that today or tomorrow. A good project XD

**Comment by gucong3000** [comment]
@ai Thank you for your trust, but I usually rely on Google and Bing to translate English, my level is limited.
