### ISSUE TITLE
Make logo clickable

### ISSUE THREAD

**Issue by ai** [ai/nanoid#74]
I think we could put a link to Nano ID repo to this logo

**Comment by hrithik-jha** [comment]
Hi I'd like to work on this. Which logo do you want to be made clickable?

**Comment by hrithik-jha** [comment]
Okay I'll get on it, but I have trouble finding the files for the webpage itself.

**Comment by ai** [comment]
Same for me :D But it is a good opportunity to learn a little of ClosureScript

**Comment by sagar-gavhane** [comment]
I think this is [website repo](https://github.com/zelark/nano-id-cc) called as Nano ID collision calculator.
