### ISSUE TITLE
Link is LOST in `README.md`

### ISSUE THREAD

**Issue by Maledong** [ai/nanoid#77]
`Secure random values (in Node.js)` in `README.md` (in both Chinese version) is LOST!

Maybe we can change to this：

https://en.wikipedia.org/wiki/Random_number_generation#Physical_methods.

**Comment by ai** [comment]
@Maledong what do you mean by `lost`?

The link is still working https://gist.github.com/joepie91/7105003c3b26e65efcea63f3db82dfba

**Comment by Maledong** [comment]
Sorry but I cannot open that link?
![lost](https://user-images.githubusercontent.com/40081831/44186762-e61cc900-a14d-11e8-99c7-26a41921d363.PNG)

So you can open that?

**Comment by ai** [comment]
Yeap, link work on my Internet.

Try VPN. Maybe domain was blocked by the government or local Internet administrator?

**Comment by Maledong** [comment]
OK, thanks！

**Comment by ai** [comment]
If VPN will not help, I can copy the page content here
