### ISSUE TITLE
Offer async version of nanoid/generate

### ISSUE THREAD

**Issue by rightaway** [ai/nanoid#80]
`nanoid/generate` can only be used synchronously, if you want to generate ids asynchronously you can't specify a custom length or alphabet.

**Comment by ai** [comment]
Good reason. I will try to do it on next week. Sorry, have a conference.

BTW, why do you need custom alphabet?

**Comment by rightaway** [comment]
Custom alphabet would be good to have for specifying exactly what would be allowed in generated URLs.

**Comment by ai** [comment]
Yeap, but what is your use case?

**Comment by ai** [comment]
Done 64017de

I will release it in next few days

**Comment by ai** [comment]
Released in 1.3
