### ISSUE TITLE
The barcode in the readme is not "NaN0~!D"

### ISSUE THREAD

**Issue by ghidosoft** [ai/nanoid#85]
Hello, I was expecting the barcode in the README to contain the string "NaN9~!D" but unfortunately it's a CODE_128 containing 141141594 😢

**Comment by ai** [comment]
@antiflasher as I remember you encoded Nano ID in barcode. Hope did you coded it (maybe we should add note how to read it).

**Comment by ai** [comment]
I think 141141594 could be converted to chat codes

**Comment by ghidosoft** [comment]
I tried some easy encoding, I even tried some javascript (but `D` is undefined and with `NaN` at the beginning it's difficult to obtain something meaningful) but I didn't decode it successfully

**Comment by ai** [comment]
`14` `1` `14` `15` `9` `4` is a `N` `A` `N` `O` `I` `D` index in alphabet

**Comment by ghidosoft** [comment]
Wow, nice, thanks for your feedback! 🙂
