### ISSUE TITLE
Can I help?  Is it possible to generate unguessable nanoid's on ReactNative?

### ISSUE THREAD

**Issue by joelgetaction** [ai/nanoid#88]
Hey,

Thanks for building this - very cool and I appreciate all the hard work you do on it!  :-)

I notice that the README says nanoid doesn't generate unpredictable ids on RN due to the lack of a secure RNG.  However, would it be possible to use something like https://www.npmjs.com/package/react-native-securerandom for example?

I was thinking to avoid a dependency on this third-party RN package, maybe we could use dependency injection to inject a secure RNG, user's choice, and give instructions for simultaneously adding this `react-native-securerandom`.  So current users would not be impacted since current defaults would work.  But new users could pass in a reference to some function that uses `react-native-securerandom` to supply the secure random bytes (via a promise).

I'd be happy to work on a PR for this if there's interest, but could you give me a few pointers where to get started in nanoid, like where to do the dependency injection and roughly how and I could give it a shot?

Thanks1

**Comment by ai** [comment]
We even don’t need tricky dependency injection. Nano ID already has `nanoid/format` to replace RNG. We can put some snippet for RN to docs.

**Comment by joelgetaction** [comment]
@ai awesome, thanks!  OK, so I could just create an example for the README showing how to use `react-native-securerandom` to create the random bytes needed for a `random` function arg to `format`?

I will do that and submit a PR, sound OK?

**Comment by joelgetaction** [comment]
The only thing is that `react-native-securerandom` is async because it crosses the RN bridge so it returns a promise.  Is that an issue for format?

**Comment by ai** [comment]
> I will do that and submit a PR, sound OK?

:+1: 

> The only thing is that react-native-securerandom is async because it crosses the RN bridge so it returns a promise. Is that an issue for format?

Oops. I will try to add async support on this weekend.

**Comment by joelgetaction** [comment]
Thanks!

**Comment by ai** [comment]
I added `nanoid/async/format` 64017de

I think snippet should be like:

```js
import { generateSecureRandom } from 'react-native-securerandom'
import format from 'nanoid/async/format'
import url from 'nanoid/url'

format(generateSecureRandom, url, 21).then(id => {
  id // random ID
})
```

I didn’t release it yet. Can you test version from GitHub and then send PR with a snippet to save your name in project’s history?

**Comment by joelgetaction** [comment]
Thanks @ai !  I will test this in the next day or two and submit a PR.

**Comment by ai** [comment]
@joelgetaction friendly ping =^_^=

**Comment by joelgetaction** [comment]
Sorry @ai busy weekend, I will do this tonight!

**Comment by joelgetaction** [comment]
Working on this right now ...

**Comment by joelgetaction** [comment]
Fixed - see https://github.com/ai/nanoid/pull/93 .  Thanks!
