### ISSUE TITLE
nanoid(0) -> "21-characters long string"

### ISSUE THREAD

**Issue by DeLaGuardo** [ai/nanoid#89]
I'm not sure that this is a big problem. But at least this is incorrect behavior.

**Comment by ai** [comment]
I can add a check and raise the error on `0`, but it will create a problem:

1. If I will put the check in `index.js` and `index.browser.js` it will increase the size of the library. It is a too big cost for the rare case.
2. If I will add check only to `index.js` it will make node/browser versions inconsistency.

What is your use case?

**Comment by DeLaGuardo** [comment]
I don't have a use case, that's why I'm not sure is this a problem). I came here cause I found the same problem in nanoid implementation for Clojure(Script) when I tried to create a generative test for it. For given `0` exception is thrown in clojure but not in nodejs. And now I'm curious which implementation is more accurate and how it should be implemented for another languages.

**Comment by ai** [comment]
I think we can close this issue, since it is a extremely rare case, which fix will cost us more then benefits

**Comment by DeLaGuardo** [comment]
But what you think about result of `nanoid(0)`? Should it be the same as without argument, exception or empty string?

**Comment by ai** [comment]
> But what you think about result of nanoid(0)

The result is non-expected. It should be an empty string.

We can fix it by replace `size = size || 21` to `if (typeof size === "undefined") size = 21`, but it will increase library size.

**Comment by DeLaGuardo** [comment]
Your answer is enough for me, thanks! And I'm not forcing you to change the library )
