### ISSUE TITLE
How about nanoid-rust?

### ISSUE THREAD

**Issue by jetbrains99** [ai/nanoid#9]
Rust has rocket framework - https://rocket.rs

> Rocket is a web framework for Rust that makes it simple to write fast web applications without sacrificing flexibility or type safety. All with minimal code.

and this module fits a lot of usecases with this. Rocket is already being used in production by dozens of companies including the big 4 internal projects. I think this module should be rewritten in rust and should comply by rocket framework semantics 👍 If you don't know about rust language, please allow me to quote rust lang book here -

> Rust is a programming language that’s focused on safety, speed, and concurrency. Its design lets you create programs that have the performance and control of a low-level language, but with the powerful abstractions of a high-level language. These properties make Rust suitable for programmers who have experience in languages like C and are looking for a safer alternative, as well as those from languages like Python who are looking for ways to write code that performs better without sacrificing expressiveness.

This will benefit a lot from a rewrite in rust lang and will improve its efficiency too while being completely safe of 99% of programming errors!

**Comment by ai** [comment]
Hi. Rust is great and port to Rust will be really great.

But I am don’t know Rust and in next few month will not have to learn it (I am focused right now on new open source Logux; Go and Elixir may be useful in Logux, but no Rust).

If you know Rust, just backport it.
